### ISSUE TITLE
Fallback to "Microsoft Visual C++ Compiler for Python 2.7" if "Visual Studio 9 2008 Win64" is not available.

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#216]
By default, if the generator `Visual Studio 9 2008 Win64` is not available, scikit-build should try to set the environment associated with "Microsoft Visual C++ Compiler for Python 2.7" and the use `NMake Makefiles` (`Ninja` generated as suggested by @thewtex [here](https://github.com/scikit-build/scikit-build/issues/34#issuecomment-236369712)).

Example of use of `NMake Makefiles` with "Microsoft Visual C++ Compiler for Python 2.7" is presented in https://github.com/scikit-build/scikit-build/issues/34#issuecomment-230070388

Let's also note that since "Microsoft Visual C++ Compiler for Python 2.7" does *NOT* provide `devenv.exe` or `msbuild.exe`, it is not possible to use CMake generator like "Visual Studio 9 2008 Win64". This is discussed in https://github.com/scikit-build/scikit-build/issues/34#issuecomment-230541130

**Comment by jcfr** [comment]
See https://github.com/pypa/setuptools/commit/b0f93f3bdd1d :  Adds monkeypatching for msvc9compiler.find_vcvarsall() to look for a standalone compiler installation and improves the error message for missing VC installation.

**Comment by jcfr** [comment]
Without `Microsoft Visual C++ Compiler for Python 2.7` installed:

```
>>> import distutils
>>> distutils.msvc9compiler.query_vcvarsall(9.0, "amd64")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\skbuild-test\lib\site-packages\setuptools\msvc.py", line 136, in msvc9_query_vcvarsall
    return EnvironmentInfo(arch, ver).return_env()
  File "C:\skbuild-test\lib\site-packages\setuptools\msvc.py", line 1097, in return_env
    [self.VCIncludes,
  File "C:\skbuild-test\lib\site-packages\setuptools\msvc.py", line 805, in VCIncludes
    return [os.path.join(self.si.VCInstallDir, 'Include'),
  File "C:\skbuild-test\lib\site-packages\setuptools\msvc.py", line 542, in VCInstallDir
    raise distutils.errors.DistutilsPlatformError(msg)
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

With `Microsoft Visual C++ Compiler for Python 2.7` installed:

```
>>> import distutils
>>> from pprint import pprint as pp
>>> pp(distutils.msvc9compiler.query_vcvarsall(9.0, "amd64"))
{u'include': u'C:\\Users\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Include;C:\\U
sers\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Include',
 u'lib': u'C:\\Users\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Lib\\amd64;C:\\Us
ers\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Lib\\x64',
 u'libpath': u'C:\\Users\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Lib\\amd64;C:
\\Users\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Lib\\x64',
 u'path': u'C:\\Users\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64;C:\\U
sers\\kitware\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Bin\\x64;C:\\Users\\kitware\\
AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Bin;C:\\skbuild-test\\Scripts;C:\\Program Fi
les (x86)\\AMD APP\\bin\\x86_64;C:\\Program Files (x86)\\AMD APP\\bin\\x86;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Python
27\\;C:\\Python27\\Scripts;C:\\Program Files (x86)\\ImageMagick-6.7.6-Q16;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\Syst
em32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;c:\\Program Files\\Intel\\DMIX;C:\\Program Files (x86)\\NTRU Cryp
tosystems\\NTRU TCG Software Stack\\bin\\;C:\\Program Files\\NTRU Cryptosystems\\NTRU TCG Software Stack\\bin\\;c:\\Program F
iles (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files (x86)\\Intel\\Services\\IPT\\;C:\\Program Files\\Dell\\D
ell Data Protection\\Access\\Advanced\\Wave\\Gemalto\\Access Client\\v5\\;C:\\Program Files (x86)\\Common Files\\Roxio Shared
\\OEM\\DLLShared\\;C:\\Program Files (x86)\\Common Files\\Roxio Shared\\OEM\\12.0\\DLLShared\\;C:\\Program Files (x86)\\Roxio
\\OEM\\AudioCore\\;C:\\Program Files (x86)\\CMake 2.8\\bin\\;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\bin\\;
C:\\Qt\\4.7.4\\bin\\;C:\\xampp\\mysql\\bin;C:\\xampp\\php;C:\\Program Files (x86)\\PostgreSQL\\8.4\\bin;C:\\dcmtk-3.6.0-win32
-i386\\bin;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Cypress\\EZ-USB FX3 SDK\\1.3\
\bin\\;C:\\Program Files (x86)\\Cypress\\EZ-USB FX3 SDK\\1.3\\jre7\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript
\\1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files\\MATLAB\\R2016b\\bin;C:\\Windows\\syste
m32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\
Tools\\Binn\\;C:\\Program Files\\SlikSvn\\bin;C:\\Program Files (x86)\\CMake\\bin;C:\\ProgramData\\chocolatey\\bin'}
```

**Comment by jcfr** [comment]
Fixed in https://github.com/scikit-build/scikit-build/commit/f437c912088e0d74b231c6e6b3bca1844b6c4b7b
