### ISSUE TITLE
Fix Python 3.4 support on windows

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#320]
Version of scikit-build: 0.6.1

See https://ci.appveyor.com/project/scikit-build/cmake-python-distributions-f3rbb/build/0.0.1.78/job/x69k10r7ffu059pg

```
CMake suite maintained and supported by Kitware (kitware.com/cmake).
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    setup_requires=setup_requires
  File "C:\Python34-x64\lib\site-packages\skbuild\setuptools_wrap.py", line 405, in setup
    cmkr = cmaker.CMaker()
  File "C:\Python34-x64\lib\site-packages\skbuild\cmaker.py", line 69, in __init__
    self.platform = get_platform()
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\platform_factory.py", line 18, in get_platform
    return windows.WindowsPlatform()
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\windows.py", line 83, in __init__
    vs_year),
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\windows.py", line 156, in __init__
    vc_env = _get_msvc_compiler_env(VS_YEAR_TO_VERSION[year])
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\windows.py", line 124, in _get_msvc_compiler_env
    from setuptools import monkey
ImportError: cannot import name 'monkey'
A command failed while executing BUILD step.
```

**Comment by jcfr** [comment]
Here is a message reported during installation:

```
scikit-build 0.6.1 has requirement setuptools>=28.0.0, but you'll have setuptools 18.2 which is incompatible.
```
