### ISSUE TITLE
Error running test_source_distribution and test_wheel

### ISSUE THREAD

**Issue by massich** [scikit-build/scikit-build#336]
https://github.com/scikit-build/scikit-build/blob/ed72d417198af0d07cbd3a9148aab14998d75fc0/tests/test_distribution.py#L22

here's the trace 
```sh
================================ ERRORS ================================
______________ ERROR at setup of test_source_distribution ______________

args = (), kwargs = {}, var = 'virtualenv_executable'
gen = <generator object virtualenv at 0x7f47de922410>

    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        for var in vars_:
            if not getattr(cfg, var):
                pytest.skip('config variable {0} missing, skipping test'.format(var))
        gen = f(*args, **kwargs)
>       yield next(gen)

../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_fixture_config.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_virtualenv.py:49: in virtualenv
    venv = VirtualEnv()
../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_virtualenv.py:140: in __init__
    self.run(cmd)
../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_virtualenv.py:148: in run
    return super(VirtualEnv, self).run(args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pytest_virtualenv.VirtualEnv object at 0x7f47de92b630>
cmd = ['/home/sik/miniconda3/envs/scipy2018-skbulid/bin/virtualenv', '-p', '/home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6', '/tmp/tmpnyppo81d/.env']
capture = False, check_rc = True, cd = Path('/tmp/tmpnyppo81d')
shell = False
kwargs = {'env': {'COLORTERM': 'truecolor', 'CONDA_DEFAULT_ENV': 'scipy2018-skbulid', 'CONDA_EXE': '/home/sik/miniconda3/bin/conda', 'CONDA_PREFIX': '/home/sik/miniconda3/envs/scipy2018-skbulid', ...}}
p = <subprocess.Popen object at 0x7f47de8b0b00>, out = None, _ = None
err = CalledProcessError(1, ['/home/sik/miniconda3/envs/scipy2018-skbulid/bin/virtualenv', '-p', '/home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6', '/tmp/tmpnyppo81d/.env'])

    def run(self, cmd, capture=False, check_rc=True, cd=None, shell=False, **kwargs):
        """
            Run a command relative to a given directory, defaulting to the workspace root
    
            Parameters
            ----------
            cmd : `str` or `list`
                Command string or list. Commands given as a string will be run in a subshell.
            capture : `bool`
                Capture and return output
            check_rc : `bool`
                Assert return code is zero
            cd : `str`
                Path to chdir to, defaults to workspace root
            """
        if isinstance(cmd, string_types):
            shell = True
        else:
            # Some of the command components might be path objects or numbers
            cmd = [str(i) for i in cmd]
    
        if not cd:
            cd = self.workspace
    
        with cmdline.chdir(cd):
            log.debug("run: {0}".format(cmd))
            if capture:
                p = subprocess.Popen(cmd, shell=shell, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs)
            else:
                p = subprocess.Popen(cmd, shell=shell, **kwargs)
            (out, _) = p.communicate()
    
            if out is not None and not isinstance(out, string_types):
                out = out.decode('utf-8')
    
            if self.debug and capture:
                log.debug("Stdout/stderr:")
                log.debug(out)
    
            if check_rc and p.returncode != 0:
                err = subprocess.CalledProcessError(p.returncode, cmd)
                err.output = out
                if capture and not self.debug:
                    log.error("Stdout/stderr:")
                    log.error(out)
>               raise err
E               subprocess.CalledProcessError: Command '['/home/sik/miniconda3/envs/scipy2018-skbulid/bin/virtualenv', '-p', '/home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6', '/tmp/tmpnyppo81d/.env']' returned non-zero exit status 1.

../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_shutil/workspace.py:132: CalledProcessError
------------------------ Captured stdout setup -------------------------
Using base prefix '/home/sik/miniconda3/envs/scipy2018-skbulid'
New python executable in /tmp/tmpnyppo81d/.env/bin/python3.6
Also creating executable in /tmp/tmpnyppo81d/.env/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /tmp/tmpnyppo81d/.env/bin/python3.6 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/cmdoptions.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/index.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/download.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/locations.py", line 87, in <module>
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.3 (default, Oct  3 2017, 21:45:48) \n[GCC 7.2.0]'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6
------------------------ Captured stderr setup -------------------------
Traceback (most recent call last):
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/tmpnyppo81d/.env/bin/python3.6 - setuptools pip wheel failed with error code 1
_____________________ ERROR at setup of test_wheel _____________________

args = (), kwargs = {}, var = 'virtualenv_executable'
gen = <generator object virtualenv at 0x7f47de9a3e08>

    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        for var in vars_:
            if not getattr(cfg, var):
                pytest.skip('config variable {0} missing, skipping test'.format(var))
        gen = f(*args, **kwargs)
>       yield next(gen)

../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_fixture_config.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_virtualenv.py:49: in virtualenv
    venv = VirtualEnv()
../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_virtualenv.py:140: in __init__
    self.run(cmd)
../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_virtualenv.py:148: in run
    return super(VirtualEnv, self).run(args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pytest_virtualenv.VirtualEnv object at 0x7f47de9195f8>
cmd = ['/home/sik/miniconda3/envs/scipy2018-skbulid/bin/virtualenv', '-p', '/home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6', '/tmp/tmpg67iih35/.env']
capture = False, check_rc = True, cd = Path('/tmp/tmpg67iih35')
shell = False
kwargs = {'env': {'COLORTERM': 'truecolor', 'CONDA_DEFAULT_ENV': 'scipy2018-skbulid', 'CONDA_EXE': '/home/sik/miniconda3/bin/conda', 'CONDA_PREFIX': '/home/sik/miniconda3/envs/scipy2018-skbulid', ...}}
p = <subprocess.Popen object at 0x7f47de919400>, out = None, _ = None
err = CalledProcessError(1, ['/home/sik/miniconda3/envs/scipy2018-skbulid/bin/virtualenv', '-p', '/home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6', '/tmp/tmpg67iih35/.env'])

    def run(self, cmd, capture=False, check_rc=True, cd=None, shell=False, **kwargs):
        """
            Run a command relative to a given directory, defaulting to the workspace root
    
            Parameters
            ----------
            cmd : `str` or `list`
                Command string or list. Commands given as a string will be run in a subshell.
            capture : `bool`
                Capture and return output
            check_rc : `bool`
                Assert return code is zero
            cd : `str`
                Path to chdir to, defaults to workspace root
            """
        if isinstance(cmd, string_types):
            shell = True
        else:
            # Some of the command components might be path objects or numbers
            cmd = [str(i) for i in cmd]
    
        if not cd:
            cd = self.workspace
    
        with cmdline.chdir(cd):
            log.debug("run: {0}".format(cmd))
            if capture:
                p = subprocess.Popen(cmd, shell=shell, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs)
            else:
                p = subprocess.Popen(cmd, shell=shell, **kwargs)
            (out, _) = p.communicate()
    
            if out is not None and not isinstance(out, string_types):
                out = out.decode('utf-8')
    
            if self.debug and capture:
                log.debug("Stdout/stderr:")
                log.debug(out)
    
            if check_rc and p.returncode != 0:
                err = subprocess.CalledProcessError(p.returncode, cmd)
                err.output = out
                if capture and not self.debug:
                    log.error("Stdout/stderr:")
                    log.error(out)
>               raise err
E               subprocess.CalledProcessError: Command '['/home/sik/miniconda3/envs/scipy2018-skbulid/bin/virtualenv', '-p', '/home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6', '/tmp/tmpg67iih35/.env']' returned non-zero exit status 1.

../../miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/pytest_shutil/workspace.py:132: CalledProcessError
------------------------ Captured stdout setup -------------------------
Using base prefix '/home/sik/miniconda3/envs/scipy2018-skbulid'
New python executable in /tmp/tmpg67iih35/.env/bin/python3.6
Also creating executable in /tmp/tmpg67iih35/.env/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /tmp/tmpg67iih35/.env/bin/python3.6 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/cmdoptions.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/index.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/download.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/locations.py", line 87, in <module>
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.3 (default, Oct  3 2017, 21:45:48) \n[GCC 7.2.0]'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /home/sik/miniconda3/envs/scipy2018-skbulid/bin/python3.6
------------------------ Captured stderr setup -------------------------
Traceback (most recent call last):
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/sik/miniconda3/envs/scipy2018-skbulid/lib/python3.6/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/tmpg67iih35/.env/bin/python3.6 - setuptools pip wheel failed with error code 1
=========== 166 passed, 26 skipped, 2 error in 41.79 seconds ===========
```

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
