### ISSUE TITLE
azure-pipeline: Fix failure to submit to codecov

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#409]
See https://dev.azure.com/scikit-build/scikit-build/_build/results?buildId=145

```
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\3ac1d451-4d92-4fff-9ca5-d6f564fff219.cmd""
    _    _____ _____ _____ ____    _____ _____ ____ _____ 
   / \  |  ___|_   _| ____|  _ \  |_   _| ____/ ___|_   _|
  / _ \ | |_    | | |  _| | |_) |   | | |  _| \___ \ | |  
 / ___ \|  _|   | | | |___|  _ <    | | | |___ ___) || |  
/_/   \_\_|     |_| |_____|_| \_\___|_| |_____|____/ |_|  
                               |_____|                    

[scikit-ci] Executing:
              import os, subprocess
              if 'CODECOV_TOKEN' in os.environ:
                  subprocess.check_call("codecov -X gcov --required --file ./tests/coverage.xml", shell=True)
              else:
                  print("Skipping codecov: CODECOV_TOKEN env. variable is not set")
The filename, directory name, or volume label syntax is incorrect.

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.15

==&gt;‌ Detecting CI provider‌
  -> Got branch from git/hg
  -> Got sha from git/hg
==&gt;‌ Preparing upload‌
    Error running `cd 'D:\a\1\s' && git ls-files`: None
XX&gt;‌ Skip processing gcov‌
==&gt;‌ Collecting reports‌
    Targeting specific files
    ‌+‌ .&#x2F;tests&#x2F;coverage.xml bytes=66928‌
==&gt;‌ Uploading‌
    .url https://codecov.io
    .query commit=e4cb08335867121258fc7cebb886ef3c3485ca30&branch=HEAD&token=<secret>&package=py2.0.15
    Pinging Codecov...
Error:‌ HTTP 400‌
Provided token is not a UUID.


Tip:‌ See all example repositories: https:&#x2F;&#x2F;github.com&#x2F;codecov?query=example‌
Support channels:‌
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\tmps0swwdxr.py", line 4, in <module>
    subprocess.check_call("codecov -X gcov --required --file ./tests/coverage.xml", shell=True)
  File "C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'codecov -X gcov --required --file ./tests/coverage.xml' returned non-zero exit status 1.

            A command failed while executing AFTER_TEST step.
              Return code:
                1
              Command:
                import os, subprocess
if 'CODECOV_TOKEN' in os.environ:
    subprocess.check_call("codecov -X gcov --required --file ./tests/coverage.xml", shell=True)
else:
    print("Skipping codecov: CODECOV_TOKEN env. variable is not set")

              Working directory:
                D:\a\1\s

            Please see above for more information.

##[error]Cmd.exe exited with code '1'.
##[section]Finishing: After Test
```

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/scikit-build/scikit-build/pull/410
