### ISSUE TITLE
Ninja selects the wrong toolchain on windows if some gcc is on the path

### ISSUE THREAD

**Issue by eric-wieser** [scikit-build/scikit-build#435]
When I run `py -3 setup.py develop --user`, I get the following output

```
--------------------------------------------------------------------------------
-- Trying "Ninja (Visual Studio 15 2017 Win64 v140)" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 5.2.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 5.2.0
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/wiese/Repos/cocotb/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja (Visual Studio 15 2017 Win64 v140)" generator - success
--------------------------------------------------------------------------------
```

Why is the "Visual Studio" generator invoking GCC?

**Comment by jcfr** [comment]
> When I run `py -3 setup.py develop --user`

To avoid specifying `--user` and allow you to easily setup a clean development environment, I suggest you create a virtual environment first.

For more information about virtual environment, see https://docs.python.org/3.6/library/venv.html

> Why is the "Visual Studio" generator invoking GCC?

Look like there is an issue in the logic looking up a working build environment.

To effectively address the problem, could you provide more details about the environment in which one you are running the command ? 

Are you running the command from a mingw or git bash terminal ?

**Comment by eric-wieser** [comment]
I'm running from a standard windows command prompt, but I have a GCC from a Haskell installation on my path. I haven't yet tried removing those binaries from my path, but I don't think I should be requires to.

**Comment by eric-wieser** [comment]
As for venv - the package I'm trying to move to this build system has flaky venv support, and I'd rather not deal with two problems at the same time.

**Comment by lyckantropen** [comment]
I can confirm this happens on the GitHub `windows-2019` image when using the [cibuildwheel](https://github.com/joerick/cibuildwheel) action. 

```
   + pip wheel D:\a\psnr_hvsm\psnr_hvsm -w C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheellcnkwkhu\built_wheel --no-deps
  Processing d:\a\psnr_hvsm\psnr_hvsm
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Building wheels for collected packages: psnr-hvsm
    Building wheel for psnr-hvsm (PEP 517): started
    Building wheel for psnr-hvsm (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'c:\cibw\python\python.3.6.8\tools\python.exe' 'c:\cibw\python\python.3.6.8\tools\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmp_1b9jp19'
         cwd: C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj
    Complete output (75 lines):
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 8.1.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 8.1.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/ProgramData/chocolatey/bin/c++.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
  Failed to build psnr-hvsm
    -- Build files have been written to: C:/Users/runneradmin/AppData/Local/Temp/pip-req-build-p7x99twj/_cmake_test_compile/build
    -- The CXX compiler identification is GNU 8.1.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/ProgramData/chocolatey/bin/c++.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-aarlsc5_/overlay/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found
      version "3.9.2")
    Call Stack (most recent call first):
      C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-aarlsc5_/overlay/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-aarlsc5_/overlay/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/FindPython/Support.cmake:2984 (find_package_handle_standard_args)
      C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-aarlsc5_/overlay/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/FindPython3.cmake:389 (include)
      psnr_hvsm/CMakeLists.txt:1 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/runneradmin/AppData/Local/Temp/pip-req-build-p7x99twj/_skbuild/win-amd64-3.6/cmake-build/CMakeFiles/CMakeOutput.log".
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-aarlsc5_\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 586, in setup
        languages=cmake_languages
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-aarlsc5_\overlay\Lib\site-packages\skbuild\cmaker.py", line 240, in configure
        os.path.abspath(CMAKE_BUILD_DIR())))
    
    
    --------------------------------------------------------------------------------
    -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator - success
    --------------------------------------------------------------------------------
    
    Configuring Project
      Working directory:
        C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj\_skbuild\win-amd64-3.6\cmake-build
      Command:
        cmake 'C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj\_skbuild\win-amd64-3.6\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\cibw\python\python.3.6.8\tools\python.exe' -DPYTHON_VERSION_STRING:STRING=3.6.8 '-DPYTHON_INCLUDE_DIR:PATH=c:\cibw\python\python.3.6.8\tools\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\cibw\python\python.3.6.8\tools\libs\python36.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-aarlsc5_\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_BUILD_TYPE:STRING=Release
    
    Traceback (most recent call last):
    
    An error occurred while configuring with CMake.
      Command:
        cmake 'C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj\_skbuild\win-amd64-3.6\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\cibw\python\python.3.6.8\tools\python.exe' -DPYTHON_VERSION_STRING:STRING=3.6.8 '-DPYTHON_INCLUDE_DIR:PATH=c:\cibw\python\python.3.6.8\tools\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\cibw\python\python.3.6.8\tools\libs\python36.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-aarlsc5_\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_BUILD_TYPE:STRING=Release
      Source directory:
        C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj
      Working directory:
        C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-p7x99twj\_skbuild\win-amd64-3.6\cmake-build
    Please see CMake's output for more information.
    ----------------------------------------
    ERROR: Failed building wheel for psnr-hvsm
  ERROR: Failed to build one or more wheels
```

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
