### ISSUE TITLE
Error Installing ninja Via pip (directed to contact scikit-build team)

### ISSUE THREAD

**Issue by AntumDeluge** [scikit-build/scikit-build#438]
I am trying to install [ninja](https://ninja-build.org/) via pip, but I get the following error where I am directed to "contact the scikit-build team":

```
$ pip install ninja
Collecting ninja
  Using cached https://files.pythonhosted.org/packages/dd/96/e2ec4acccb8dee33b4987f553d531d61e3081c8d4cfbce249655dfe23906/ninja-1.9.0.post1.tar.gz
Building wheels for collected packages: ninja
  Building wheel for ninja (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3.exe -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-xrvhonee/ninja/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7cvdk_ol --python-tag cp37:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xrvhonee/ninja/setup.py", line 75, in <module>
      setup_requires=setup_requires
    File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 548, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/usr/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in __init__
      self.platform = get_platform()
    File "/usr/lib/python3.7/site-packages/skbuild/platform_specifics/platform_factory.py", line 27, in get_platform
      "the scikit-build team.".format(this_platform))
  RuntimeError: Unsupported platform: mingw64_nt-10.0-17763. Please contact the scikit-build team.
  ----------------------------------------
  ERROR: Failed building wheel for ninja
  Running setup.py clean for ninja
Failed to build ninja
Installing collected packages: ninja
  Running setup.py install for ninja ... error
    ERROR: Complete output from command /usr/bin/python3.exe -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-xrvhonee/ninja/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3vq3j2af/install-record.txt --single-version-externally-managed --compile:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xrvhonee/ninja/setup.py", line 75, in <module>
        setup_requires=setup_requires
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 548, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/usr/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in __init__
        self.platform = get_platform()
      File "/usr/lib/python3.7/site-packages/skbuild/platform_specifics/platform_factory.py", line 27, in get_platform
        "the scikit-build team.".format(this_platform))
    RuntimeError: Unsupported platform: mingw64_nt-10.0-17763. Please contact the scikit-build team.
    ----------------------------------------
ERROR: Command "/usr/bin/python3.exe -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-xrvhonee/ninja/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3vq3j2af/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xrvhonee/ninja/
```

---
System & platform information:

OS: Microsoft Windows 10 64-bit
Python & pip info:
```sh
$ python --version
Python 3.7.4

$ python -c 'import sys; print("64-bit: {}".format(sys.maxsize > 2**32))'
64-bit: True

$ pip --version
pip 19.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)

$ pip search ninja
ninja (1.9.0.post1)                               - Ninja is a small build
                                                    system with a focus on
                                                    speed
...

$ pip search scikit-build
scikit-build (0.10.0)                 - Improved build system generator for
                                        Python C/C++/Fortran/Cython extensions
  INSTALLED: 0.10.0 (latest)
...
```

**Comment by jcfr** [comment]
Thanks for the report. 

To troubleshoot, could you run the following code on your system:

```
from pip._internal.pep425tags import get_supported
print('\n'.join('-'.join(x) for x in get_supported()))
```

**Comment by AntumDeluge** [comment]
My problem seems to have been corrected. I made some changes to PATH environment variable. It appears that there may have been interference from multiple Python installations, but I'm not sure exactly what fixed it:

```sh
$ pip install ninja
Collecting ninja
  Downloading https://files.pythonhosted.org/packages/7b/25/6e388c2b1b64a433b165f51465ca4e46142c8044c4c75e252c2252c40af1/ninja-1.9.0.post1-py3-none-win_amd64.whl (232kB)
     |████████████████████████████████| 235kB 819kB/s
Installing collected packages: ninja
Successfully installed ninja-1.9.0.post1
```

Just in case, here is the output requested:

Python 3:
```python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pip._internal.pep425tags import get_supported
>>> print('\n'.join('-'.join(x) for x in get_supported()))
cp37-cp37m-win_amd64
cp37-none-win_amd64
py3-none-win_amd64
cp37-none-any
cp3-none-any
py37-none-any
py3-none-any
py36-none-any
py35-none-any
py34-none-any
py33-none-any
py32-none-any
py31-none-any
py30-none-any
```

Python 2:
```python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pip._internal.pep425tags import get_supported
>>> print('\n'.join('-'.join(x) for x in get_supported()))
cp27-cp27m-win_amd64
cp27-none-win_amd64
py2-none-win_amd64
cp27-none-any
cp2-none-any
py27-none-any
py2-none-any
py26-none-any
py25-none-any
py24-none-any
py23-none-any
py22-none-any
py21-none-any
py20-none-any
```

**Note:** I am using [MSYS2/MinGW-64](https://www.msys2.org/), which has its own Python implementations. I ***believe*** what fixed my problem was to list my system Python installations in PATH variable ahead of MSYS2 paths, giving them priority.

**Comment by jcfr** [comment]
That makes sense. Thanks for updating and closing the issue :+1:

**Comment by FFY00** [comment]
I ran into the same issue.

```
      Traceback (most recent call last):
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-2pos24p_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-2pos24p_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-2pos24p_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
        File "/tmp/pip-build-env-2pos24p_/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 612, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-2pos24p_/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 150, in __init__
          self.platform = get_platform()
        File "/tmp/pip-build-env-2pos24p_/overlay/lib/python3.10/site-packages/skbuild/platform_specifics/platform_factory.py", line 42, in get_platform
          raise RuntimeError(msg)
      RuntimeError: Unsupported platform: mingw64_nt-10.0-19041. Please contact the scikit-build team.
```

> I _**believe**_ what fixed my problem was to list my system Python installations in PATH variable ahead of MSYS2 paths, giving them priority.

This is just a workaround, the issue is still present.

There's no reason for scikit-build to not work with a MinGW provided Python. @jcfr would it be possible to re-open?
