### ISSUE TITLE
Build IBMQ qiskit-aer on IBM i - "Unsupported platform: os400"

### ISSUE THREAD

**Issue by jwoehr** [scikit-build/scikit-build#444]
Pull requests over the past few months have been accepted to allow scikit-build to run on IBM i PASE ("os400").

Building IBM Q qiskit-aer on IBM i with fresh pip install of scikit-build 0.10.0 yields the following:
```
$ python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    keywords="qiskit aer simulator quantum addon backend"
  File "/home/DRIVEWAY/jwoehr/Qiskit/qdev_venv/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 548, in setup
    cmkr = cmaker.CMaker(cmake_executable)
  File "/home/DRIVEWAY/jwoehr/Qiskit/qdev_venv/lib/python3.6/site-packages/skbuild/cmaker.py", line 95, in __init__
    self.platform = get_platform()
  File "/home/DRIVEWAY/jwoehr/Qiskit/qdev_venv/lib/python3.6/site-packages/skbuild/platform_specifics/platform_factory.py", line 27, in get_platform
    "the scikit-build team.".format(this_platform))
RuntimeError: Unsupported platform: os400. Please contact the scikit-build team.
```
Will you need a pull request or can this be tracked down by the sckit-build team?

**Comment by jcfr** [comment]
Closing. Fix integrated in https://github.com/scikit-build/scikit-build/commit/8c79cff87974d52d0ec9a6c31c54a7fbf51cbf61
