### ISSUE TITLE
f2py: example of use

### ISSUE THREAD

**Issue by scivision** [scikit-build/scikit-build#468]
I have a number of f2py-based projects that I would like to build with skbuild instead of distutils.
I am trying to get my first project going with skbuild, it is a single Fortran 77 file lowtran7.f and scikit-build 0.10.0 (or git master scikit-build)

I have [attempted](https://github.com/space-physics/lowtran/tree/skbuild) this using
* [CMakeLists.txt](https://github.com/space-physics/lowtran/blob/skbuild/CMakeLists.txt)
* [lowtran/CMakeLists.txt](https://github.com/space-physics/lowtran/blob/skbuild/lowtran/CMakeLists.txt)

but upon `python setup.py develop` (on Windows or Ubuntu) I get Ninja error

```
ninja: warning: phony target 'lowtran/_lowtran7' names itself as an input; ignoring [-w phonycycle=warn]
ninja: error: build.ninja:213: multiple rules generate lowtran/_lowtran7 [-w dupbuild=err]

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\skbuild\setuptools_wrap.py", line 577, in setup
    cmkr.make(make_args, env=env)
  File "C:\Miniconda3\lib\site-packages\skbuild\cmaker.py", line 482, in make
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while building with CMake.
  Command:
    "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
  Source directory:
   lowtran
  Working directory:
   lowtran\_skbuild\win-amd64-3.7\cmake-build
```

**Comment by Nicholaswogan** [comment]
I would also appreciate some f2py examples. I have tried and failed to use skbuild for my f2py projects.

**Comment by Nicholaswogan** [comment]
I put together some examples: https://github.com/Nicholaswogan/skbuild-f2py-examples . If you all are interested in a pull request with one of these examples let me know.

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
