### ISSUE TITLE
ImportError on MacOS

### ISSUE THREAD

**Issue by AntoinePrv** [scikit-build/scikit-build#472]
Hello,

Thank you for your work done on this project!

When running `python -c import skbuild` on MacOS, with both `0.10.0` and `master`, the get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../python3.8/site-packages/skbuild/__init__.py", line 9, in <module>
    from .setuptools_wrap import setup  # noqa: F401
  File ".../python3.8/site-packages/skbuild/setuptools_wrap.py", line 39, in <module>
    from . import cmaker
  File ".../python3.8/site-packages/skbuild/cmaker.py", line 24, in <module>
    from .platform_specifics import get_platform
  File ".../python3.8/site-packages/skbuild/platform_specifics/__init__.py", line 6, in <module>
    from .platform_factory import get_platform   # noqa: F401
  File ".../python3.8/site-packages/skbuild/platform_specifics/platform_factory.py", line 7, in <module>
    from . import linux
  File ".../python3.8/site-packages/skbuild/platform_specifics/linux.py", line 3, in <module>
    import distro
  File "/.../python3.8/site-packages/distro.py", line 42, in <module>
    raise ImportError('Unsupported platform: {0}'.format(sys.platform))
ImportError: Unsupported platform: darwin
```

I may come from a recent change in the `distro` package.

An alternative could be to lazily load platforms, by moving the import statement
https://github.com/scikit-build/scikit-build/blob/0c33f15b0c0452e8bd70ab6057b4d283d6025b51/skbuild/platform_specifics/platform_factory.py#L7
inside this condition:
```python
if this_platform == "linux":
    from . import linux
    return linux.LinuxPlatform()
```

I'm willing to send a PR for the aforementioned change.

**Comment by jcfr** [comment]
Thanks for the report 🙏 

> I'm willing to send a PR for the aforementioned change.

That would be great 😄 

While doing so, make sure to add an entry to [CHANGES.rst](https://github.com/scikit-build/scikit-build/blob/master/CHANGES.rst). Referencing the upstream commit introducing the change to `platform` would be ideal.

**Comment by AntoinePrv** [comment]
OK, seems like I had it the other way around: I had `distro<1.2.0`, (currently `1.4.0`) from other requirements.

This `ImportError` was removed in `1.2.0`
https://github.com/nir0s/distro/releases/tag/v1.2.0

This is not urgent for me so I will simply try get the version number of `distro` in other dependencies.
