### ISSUE TITLE
Unsupported platform darwin with distro < 1.2.0

### ISSUE THREAD

**Issue by Chrismarsh** [scikit-build/scikit-build#488]
I use `conan` to drive the dependency resolution of my backend `cmake` build.

However, `conan` has a `distro<1.2.0` [requirement](https://github.com/conan-io/conan/blob/e498cefbc8e89308d2f0570707d51a3405401368/conans/requirements.txt#L10).

Therefore, when using `distro==1.1.0` to be compatible with `conan` the new 0.11 release of scikit-build fails on macos with this error:

```
Traceback (most recent call last):

    File "/Users/travis/.pyenv/versions/3.7.6/envs/mesher/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>

      main()

    File "/Users/travis/.pyenv/versions/3.7.6/envs/mesher/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main

      json_out['return_val'] = hook(**hook_input['kwargs'])

    File "/Users/travis/.pyenv/versions/3.7.6/envs/mesher/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel

      return hook(config_settings)

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 148, in get_requires_for_build_wheel

      config_settings, requirements=['wheel'])

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires

      self.run_setup()

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 250, in run_setup

      self).run_setup(setup_script=setup_script)

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in run_setup

      exec(compile(code, __file__, 'exec'), locals())

    File "setup.py", line 1, in <module>

      from skbuild import setup

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/skbuild/__init__.py", line 9, in <module>

      from .setuptools_wrap import setup  # noqa: F401

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 39, in <module>

      from . import cmaker

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 24, in <module>

      from .platform_specifics import get_platform

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/skbuild/platform_specifics/__init__.py", line 6, in <module>

      from .platform_factory import get_platform   # noqa: F401

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/skbuild/platform_specifics/platform_factory.py", line 7, in <module>

      from . import linux

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/skbuild/platform_specifics/linux.py", line 3, in <module>

      import distro

    File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-build-env-u2ybr7kw/overlay/lib/python3.7/site-packages/distro.py", line 42, in <module>

      raise ImportError('Unsupported platform: {0}'.format(sys.platform))

  ImportError: Unsupported platform: darwin```
```

I suspect this is related to #472. Explicitly setting `"scikit-build==0.10.0"` in my `pyproject.toml` resolves this.

**Comment by jcfr** [comment]
Thanks for reporting the issue :pray: 

When you have a chance, it would be great to confirm that this updates version fixes the issue. 

You could test doing the following:

```
pip uninstall scikit-build
pip install git+https://github.com/jcfr/scikit-build.git@472-lazily-load-platform-to-support-conan
```

**Comment by Chrismarsh** [comment]
Resolved on my end, thanks!

**Comment by jcfr** [comment]
> Resolved on my end, thanks!

Great, I will release scikit-build 0.11.1 later tonight then.

**Comment by jcfr** [comment]
Et voila, scikit-build 0.11.1 is out. Thanks for your patience :pray: 

![image](https://user-images.githubusercontent.com/219043/81273286-aa5e1d00-901c-11ea-9713-ea0f85c443e8.png)
