### ISSUE TITLE
`pip install .` should invalidate CMake cache in temporary directory

### ISSUE THREAD

**Issue by kkraus14** [scikit-build/scikit-build#521]
If someone has run a `pip install -e .` or a `python setup.py build_ext --inplace` it will create a CMake cache in the source directory. If someone tries to run `pip install .` afterwards it seems like the cache is being copied into the temporary directory created by pip and still references the source directory which causes a failure which is caught and then falls back to `python setup.py install` (which is deprecated behavior):
```
(dev) keith@Keith-PC:~/git/rmm/python$ pip install -e .
Obtaining file:///home/keith/git/rmm/python
Installing collected packages: rmm
  Attempting uninstall: rmm
    Found existing installation: rmm 0.17.0
    Uninstalling rmm-0.17.0:
      Successfully uninstalled rmm-0.17.0
  Running setup.py develop for rmm
Successfully installed rmm
```
```
(dev) keith@Keith-PC:~/git/rmm/python$ pip install .
Processing /home/keith/git/rmm/python
Building wheels for collected packages: rmm
  Building wheel for rmm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/keith/miniconda3/envs/dev/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1p0o94xr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1p0o94xr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-htxv7twc
       cwd: /tmp/pip-req-build-1p0o94xr/
  Complete output (22 lines):
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-1p0o94xr/_skbuild/linux-x86_64-3.7/cmake-build/CMakeCache.txt is different than the directory /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  [0/1] Install the project...
  -- Install configuration: "Release"
  -- Up-to-date: /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-install/rmm/_cuda/gpu.so
  -- Up-to-date: /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-install/rmm/_lib/device_buffer.so
  -- Up-to-date: /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-install/rmm/_lib/lib.so
  -- Up-to-date: /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-install/rmm/_lib/memory_resource.so
  -- Up-to-date: /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-install/rmm/_lib/cuda_stream_view.so
  -- Up-to-date: /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-install/rmm/tests/test_device_buffer.so
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-1p0o94xr/setup.py", line 29, in <module>
      zip_safe=False,
    File "/home/keith/miniconda3/envs/dev/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 625, in setup
      cmake_source_dir, skbuild_kw['cmake_install_dir'])
    File "/home/keith/miniconda3/envs/dev/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 757, in _classify_installed_files
      install_root, to_platform_path(path)))
  skbuild.exceptions.SKBuildError:
    CMake-installed files must be within the project root.
      Project Root  : /tmp/pip-req-build-1p0o94xr/_skbuild/linux-x86_64-3.7/cmake-install
      Violating File: /home/keith/git/rmm/python/_skbuild/linux-x86_64-3.7/cmake-install/rmm/_cuda/gpu.so

  ----------------------------------------
  ERROR: Failed building wheel for rmm
  Running setup.py clean for rmm
Failed to build rmm
Installing collected packages: rmm
  Attempting uninstall: rmm
    Found existing installation: rmm 0.17.0
    Uninstalling rmm-0.17.0:
      Successfully uninstalled rmm-0.17.0
    Running setup.py install for rmm ... done
  DEPRECATION: rmm was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed rmm-0.17.0
```

**Comment by casperdcl** [comment]
A work-around is:

```bash
sed -ni 's/^[^#].*pip-build-env.*//' ./_skbuild/*/cmake-build/CMakeCache.txt
pip install -e .
```

Really, `scikit-build` should remove temporary pip-build-env entries from the cache itself.

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
