### ISSUE TITLE
Sckit build unable to build with Geographic lib, despite lib not having problems outside of scikitbuild

### ISSUE THREAD

**Issue by Cazadorro** [scikit-build/scikit-build#603]
I've got a library which depends on Geographic Lib, https://github.com/geographiclib/, among other libraries.  I use GeographicLib as a static subdirectory in my project, in addition to other libraries. I create the following dummy file structure to reproduce this issue (based off of the hello cython example): 
```

* cython_example
    * my_library/
        * external/
            * liba/
            * libb/
            * geographiclib/
        * CMakeLists.txt
        * my_library_test.h
        * my_library_test.cpp
    * hello/
        * ...
    * CMakeLists.txt
    * pyproject.toml
    * setup.py
```

Where my source files are just

my_library_test.h    
```
#ifndef MY_LIBRARY_MY_LIBRARY_TEST_H
#define MY_LIBRARY_MY_LIBRARY_TEST_H
namespace test{
    int foo();
}
#endif //MY_LIBRARY_MY_LIBRARY_TEST_H
```

and 

my_library_test.cpp
```
#include "my_library_test.h"

int test::foo() {
    return 0;
}
```
The "my_library" CMakeLists.txt is just

```
cmake_minimum_required(VERSION 3.13)  # CMake version check
project(my_library_main)
set(CMAKE_CXX_STANDARD 17)

if (NOT TARGET liba::liba)
    add_subdirectory(external/liba)
endif()

add_library(my_library_test)
target_sources(my_library_test PUBLIC my_library_test.cpp my_library_test.h)
set(GEOGRAPHICLIB_LIB_TYPE STATIC CACHE STRING "")
add_subdirectory(external/geographiclib)
```

and the hello CMakeLists.txt is just the same thing in the example provided, plus a dependency on my new library
```

add_cython_target(_hello CXX)
add_library(_hello MODULE ${_hello})
target_link_libraries(_hello
my_library_test
)

python_extension_module(_hello)

install(TARGETS _hello LIBRARY DESTINATION hello)
```

The following scenarios work perfectly:

* Using my library as a dependency of another C++ project (and actually using geographiclib in code, not the dummy version I show here). 
* Compiling and using Geographic Lib independently as both a static and dynamic library outside of Scikit build
* Using Scikit build to build my library with out Geographic Lib using the dummy files here, but still with dependencies on build only (no install targets) libraries for `liba` and `libb`

The following situation doesn't work: 

* Using Scikit build to build my library **with** Geographic Lib using the dummy files here, but still with dependencies on build only (no install targets) libraries for `liba` and `libb`

Running, in a custom 3.8 environment (not global), the following command:

`python setup.py build`

results in the following output:
```

/home/user/Documents/projects/python_test/envs/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(


--------------------------------------------------------------------------------
-- Trying "Ninja" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 8.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-8/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 8.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-8/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Documents/projects/python_test/cython_example/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja" generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-build
  Command:
    cmake /home/user/Documents/projects/python_test/cython_example -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/user/Documents/projects/python_test/envs/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.8 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/local/lib/libpython3.8.a -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/user/Documents/projects/python_test/envs/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-8/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-8/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /home/user/Documents/projects/python_test/envs/bin/python (found version "3.8.8") 
-- Found PythonLibs: /usr/local/lib/libpython3.8.a (found version "3.8.8") 
-- Found Cython: /home/user/Documents/projects/python_test/envs/bin/cython  
-- Check size of long double
-- Check size of long double - done
-- Check size of double
-- Check size of double - done
-- Performing Test FLOAT_CONVERSION
-- Performing Test FLOAT_CONVERSION - Success
-- Performing Test CXX11_MATH
-- Performing Test CXX11_MATH - Success
-- Performing Test CXX11_STATIC_ASSERT
-- Performing Test CXX11_STATIC_ASSERT - Success
-- Performing Test CXX11_RANDOM
-- Performing Test CXX11_RANDOM - Success
-- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
_modinit_prefix:PyInit_
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    SKBUILD


-- Build files have been written to: /home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-build
[74/107] Generating geographiclib.js, geographiclib.min.js
FAILED: my_library/external/geographiclib/js/geographiclib.js my_library/external/geographiclib/js/geographiclib.min.js /home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-build/my_library/external/geographiclib/js/geographiclib.js /home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-build/my_library/external/geographiclib/js/geographiclib.min.js 
cd /home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-build/my_library/external/geographiclib && /home/user/Documents/projects/python_test/envs/lib/python3.8/site-packages/cmake/data/bin/cmake .
CMake Error: The source directory "/home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-build/my_library/external/geographiclib" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
[79/107] Building CXX object my_library/external/geographiclib/src/CMakeFiles/GeographicLib_STATIC.dir/SphericalEngine.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/user/Documents/projects/python_test/envs/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 593, in setup
    cmkr.make(make_args, env=env)
  File "/home/user/Documents/projects/python_test/envs/lib/python3.8/site-packages/skbuild/cmaker.py", line 504, in make
    raise SKBuildError(

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Source directory:
    /home/user/Documents/projects/python_test/cython_example
  Working directory:
    /home/user/Documents/projects/python_test/cython_example/_skbuild/linux-x86_64-3.8/cmake-build
Please see CMake's output for more information.
```

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
