### ISSUE TITLE
'_collections._tuplegetter' object has no attribute 'split'

### ISSUE THREAD

**Issue by tdegeus** [scikit-build/scikit-build#643]
On cross-compiling on macOS I'm getting:
```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from skbuild import setup
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/__init__.py", line 9, in <module>
    from .setuptools_wrap import setup  # noqa: F401
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 39, in <module>
    from . import cmaker
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/cmaker.py", line 20, in <module>
    from .constants import (CMAKE_BUILD_DIR,
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/constants.py", line 62, in <module>
    _SKBUILD_PLAT_NAME = _default_skbuild_plat_name()
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/constants.py", line 56, in _default_skbuild_plat_name
    if set(machine.split(";")) == macos_universal2_architectures:
AttributeError: '_collections._tuplegetter' object has no attribute 'split'
```
Reference: https://github.com/conda-forge/frictionqpotfem-feedstock/pull/57

I'm using:
```
scikit-build:          0.12.0-py38h6f2b01f_2         conda-forge
```

**Comment by henryiii** [comment]
Could you print out what that NamedTuple is? An easy way to do that would be to temporarily add rich then put 

```python
from rich.traceback import install
install(show_locals=True)
```

at the top of your setup.py.

**Comment by tdegeus** [comment]
@henryiii is this what you need:

```
│    53 │   machine = os.environ.get("CMAKE_OSX_ARCHITECTURES", machine)       │
│    54 │                                                                      │
│    55 │   # Handle universal2 wheels, if those two architectures are request │
│ ❱  56 │   if set(machine.split(";")) == macos_universal2_architectures:      │
│    57 │   │   machine = "universal2"                                         │
│    58 │                                                                      │
│    59 │   return "macosx-{}.{}-{}".format(major_macos, minor_macos, machine) │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │                              _ = ('', '', '')                            │ │
│ │                      archflags = None                                    │ │
│ │                        machine = _tuplegetter(4, 'Alias for field number │ │
│ │                                  4')                                     │ │
│ │ macos_universal2_architectures = {'arm64', 'x86_64'}                     │ │
│ │                    major_macos = '11'                                    │ │
│ │                    minor_macos = '0'                                     │ │
│ │                        release = '11.0'                                  │ │
│ │  supported_macos_architectures = {'arm64', 'x86_64'}                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
```

If not the output is here : https://github.com/conda-forge/frictionqpotfem-feedstock/pull/59 (for macOS ARM)

**Comment by tdegeus** [comment]
```
('11.0', ('', '', ''), <_collections._tuplegetter object at 0x7ffca5124790>)
```
but I guess you want the `_collections._tuplegetter`?

**Comment by henryiii** [comment]
That must be Conda's fault, the Python docs promise this will be `tuple[str, tuple[str, str, str], str]`. Hopefully that's enough for me to dig out where Conda is doing this.

**Comment by henryiii** [comment]
What about `os.uname().machine`?

**Comment by henryiii** [comment]
(If you want to add me to your fork, I can debug there instead if you'd like)

**Comment by henryiii** [comment]
This is weird. We could probably fix is by switching to `os.uname().machine`, since `mac_ver` is a simple function that basically just returns that in the third tuple element. But how is this _not_ returning that???

https://github.com/python/cpython/blob/024209401ebc8a011f242af00efdd8ecece6953d/Lib/platform.py#L443 returns https://github.com/python/cpython/blob/024209401ebc8a011f242af00efdd8ecece6953d/Lib/platform.py#L423 and there's really not any path around that.

**Comment by henryiii** [comment]
Hmm, interestingly, this is field 4 of a NamedTuple (`os.uname()`'s return).

**Comment by henryiii** [comment]
Could you try applying #646 and see if that fixes it? From the debug printout, it seems like it will, even though I don't know why.

**Comment by tdegeus** [comment]
@henryiii Thanks a lot for the debugging. I will try https://github.com/scikit-build/scikit-build/pull/646 . In the meantime this should potentially be considered an upstream bug?
