### ISSUE TITLE
Error when installing in development mode

### ISSUE THREAD

**Issue by romankempt** [scikit-build/scikit-build#697]
**Describe the bug**
Installing a project via `pip install .` works, but fails when trying to install in development mode (either `pip install -e .` or `python setup.py develop`).

The error is triggered here:
```
Traceback (most recent call last):
  File "/mnt/c/Users/rkempt/Repositories/hetbuilder/setup.py", line 39, in <module>
    setup(
  File "/home/rkempt/miniconda3/envs/hetbuilder/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 701, in setup
    package_file = os.path.join(package_dir[package], package_file)
KeyError: ''
```

The source code of the relevant function is here:

```python
    if developer_mode:
        # Copy packages
        for package, package_file_list in package_data.items():
            for package_file in package_file_list:
                package_file = os.path.join(package_dir[package], package_file)
                cmake_file = os.path.join(CMAKE_INSTALL_DIR(), package_file)
                if os.path.exists(cmake_file):
                    _copy_file(cmake_file, package_file, hide_listing)
```

I suspect some package variable is not set correctly for development mode?

**To Reproduce**

My `setup.py` looks like this:

```python
setup(
    name="hetbuilder",
    version=version,
    author="Roman Kempt",
    author_email="roman.kempt@tu-dresden.de",
    description="A tool to build heterostructure interfaces based on coincidence lattice theory.",
    long_description=long_description,
    license="MIT",
    url="https://github.com/romankempt/hetbuilder.git",
    download_url="https://github.com/romankempt/hetbuilder.git",
    packages=find_packages(),
    package_data={"": ["*.xyz", "CMakeLists.txt"]},
    # package_dir={"": ""},
    cmake_install_dir="hetbuilder",
    include_package_data=True,
    scripts=["bin/hetbuilder"],
    install_requires=[
        "numpy",
        "scipy",
        "spglib",
        "matplotlib",
        "ase",
        "networkx",
        "pretty_errors",
        "rich",
        "typer",
        "pybind11",
    ],
    classifiers=[
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: C++",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    cmake_args=[
        "-DCMAKE_BUILD_TYPE={}".format("RELEASE"),  # not used on MSVC, but no harm,
    ],
    zip_safe=False,
)
```

**Expected behavior**
A development installation in the source directory.

**Desktop (please complete the following information):**
 - OS: WSL2

**Comment by henryiii** [comment]
Unrelated; I'd be really suprised if you need pybind11 at runtime - it's used to build code only. Unless you really are "JIT"ing code at runtime, but then you are not including scikit-build or setuptools at runtime. You almost certainly want that in your pyproject.toml `build-system requirements`, and not in your install-requires.

Anyway, we've had issues getting editable mode to work (#582 being one attempt). The good news is editable mode really isn't very useful, since you will always have to rebuild to change compiled code, so only edits to the python files would be "editable". If we can get a good reproducer (I've had trouble just getting it to fail), that would be a big help!

**Comment by romankempt** [comment]
hm, the `pyproject.toml` looks like this, if you are referring to that:
```
[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "scikit-build",
  "cmake",
  "pybind11",
  "numpy",
  "spglib",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"
```

I find the development mode pretty useful when the C++ part is just there for acceleration and I'm only working on the python files.

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
