### ISSUE TITLE
RuntimeError: Unsupported platform: cygwin_nt-6.1-7601. Please contact the scikit-build team.

### ISSUE THREAD

**Issue by alex77g2** [scikit-build/scikit-build#706]
I'm running Cygwin (64bit, from https://cygwin.com/ ).

$ uname -a
CYGWIN_NT-6.1 Quadro 3.3.4(0.341/5/3) 2022-01-31 19:35 x86_64 Cygwin

$ python3 --version
Python 3.9.10

$ pip3 --version
pip 22.0.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

# The following command fails.
$ pip3 install opencv-python
Collecting opencv-python
  Using cached opencv-python-4.5.5.64.tar.gz (89.9 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
      Collecting setuptools
        Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting scikit-build
        Using cached scikit_build-0.14.1-py2.py3-none-any.whl (76 kB)
      Collecting cmake
        Using cached cmake-3.22.4.tar.gz (31 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting pip
        Using cached pip-22.0.4-py3-none-any.whl (2.1 MB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3-cp39-cp39-cygwin_3_3_4_x86_64.whl
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting distro
        Using cached distro-1.7.0-py3-none-any.whl (20 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
      Building wheels for collected packages: cmake
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cmake (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [22 lines of output]
            Traceback (most recent call last):
              File "/tmp/tmpj699euzz_in_process.py", line 363, in <module>
                main()
              File "/tmp/tmpj699euzz_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/tmp/tmpj699euzz_in_process.py", line 261, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/tmp/pip-build-env-375b2680/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
              File "/tmp/pip-build-env-375b2680/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
                self.run_setup()
              File "/tmp/pip-build-env-375b2680/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 32, in <module>
                setup(
              File "/tmp/pip-build-env-375b2680/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/tmp/pip-build-env-375b2680/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 142, in __init__
                self.platform = get_platform()
              File "/tmp/pip-build-env-375b2680/overlay/lib/python3.9/site-packages/skbuild/platform_specifics/platform_factory.py", line 35, in get_platform
                raise RuntimeError(msg)
            RuntimeError: Unsupported platform: cygwin_nt-6.1-7601. Please contact the scikit-build team.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by henryiii** [comment]
See https://github.com/scikit-build/scikit-build/pull/485.

**Comment by poikilos** [comment]
@alex77g2 The PR was merged and 0.15.0 installs for me on Cygwin (after `pip3 install --upgrade pip wheel setuptools`).

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
