### ISSUE TITLE
Cannot install on Apple Silicon

### ISSUE THREAD

**Issue by hameer-spire** [scikit-build/scikit-build#717]
Running either of `pip install .` or `python -m build` on the [`hello_cpp` sample project](https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects/hello-cpp) fails with:

<details><summary>Log output</summary>

```
Processing /Users/hameerabbasi/Code/scikit-build-sample-projects/projects/hello-cpp
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: hello-cpp
  Building wheel for hello-cpp (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hello-cpp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [117 lines of output]
      Not searching for unused variables given on the command line.
      -- The C compiler identification is Clang 13.0.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-clang - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is Clang 13.0.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-clang++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /Users/hameerabbasi/Code/scikit-build-sample-projects/projects/hello-cpp/_cmake_test_compile/build
      _modinit_prefix:PyInit_
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /Users/hameerabbasi/Code/scikit-build-sample-projects/projects/hello-cpp/_skbuild/macosx--arm64-3.10/cmake-build
      [0/1] Install the project...
      -- Install configuration: "Release"
      -- Up-to-date: /Users/hameerabbasi/Code/scikit-build-sample-projects/projects/hello-cpp/_skbuild/macosx--arm64-3.10/cmake-install/hello/_hello.cpython-310-darwin.so


      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /Users/hameerabbasi/Code/scikit-build-sample-projects/projects/hello-cpp/_skbuild/macosx--arm64-3.10/cmake-build
        Command:
          cmake /Users/hameerabbasi/Code/scikit-build-sample-projects/projects/hello-cpp -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/hameerabbasi/Code/scikit-build-sample-projects/projects/hello-cpp/_skbuild/macosx--arm64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/python3.10 -DPython3_INCLUDE_DIR:PATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/include/python3.10 -DPython3_LIBRARY:PATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/lib/libpython3.10.dylib -DPython_EXECUTABLE:FILEPATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/python3.10 -DPython_INCLUDE_DIR:PATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/include/python3.10 -DPython_LIBRARY:PATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/lib/libpython3.10.dylib -DPYTHON_EXECUTABLE:FILEPATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/python3.10 -DPYTHON_INCLUDE_DIR:PATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/include/python3.10 -DPYTHON_LIBRARY:PATH=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/lib/libpython3.10.dylib -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DCMAKE_AR=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_CXX_COMPILER_AR=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_C_COMPILER_AR=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_RANLIB=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_C_COMPILER_RANLIB=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_LINKER=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ld -DCMAKE_STRIP=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-strip -DCMAKE_INSTALL_NAME_TOOL=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-install_name_tool -DCMAKE_LIBTOOL=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING= -DCMAKE_OSX_ARCHITECTURES:STRING=arm64 -DCMAKE_AR=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_CXX_COMPILER_AR=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_C_COMPILER_AR=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_RANLIB=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_C_COMPILER_RANLIB=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_LINKER=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-ld -DCMAKE_STRIP=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-strip -DCMAKE_INSTALL_NAME_TOOL=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-install_name_tool -DCMAKE_LIBTOOL=/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/bin/arm64-apple-darwin20.0.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk


      copying hello/__init__.py -> _skbuild/macosx--arm64-3.10/cmake-install/hello/__init__.py

      running bdist_wheel
      running build
      running build_py
      copying _skbuild/macosx--arm64-3.10/cmake-install/hello/__init__.py -> _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/hello
      copied 1 files
      running build_ext
      installing to _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel
      running install
      running install_lib
      copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/hello/__init__.py -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/hello
      copied 2 files
      running install_egg_info
      running egg_info
      writing hello_cpp.egg-info/PKG-INFO
      writing dependency_links to hello_cpp.egg-info/dependency_links.txt
      writing top-level names to hello_cpp.egg-info/top_level.txt
      reading manifest file 'hello_cpp.egg-info/SOURCES.txt'
      writing manifest file 'hello_cpp.egg-info/SOURCES.txt'
      removing '_skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/hello_cpp-1.2.3-py3.10.egg-info' (and everything under it)
      Copying hello_cpp.egg-info to _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/hello_cpp-1.2.3-py3.10.egg-info
      running install_scripts
      copied 0 files
      Traceback (most recent call last):
        File "/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/hameerabbasi/mambaforge/envs/pygnssr2-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 3, in <module>
          setup(
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 750, in setup
          return setuptools.setup(*args, **kw)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/skbuild/command/bdist_wheel.py", line 40, in run
          super(bdist_wheel, self).run(*args, **kwargs)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 337, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 260, in get_tag
          plat_name = get_platform(self.bdist_dir)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 52, in get_platform
          result = calculate_macosx_platform_tag(archive_root, result)
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 366, in calculate_macosx_platform_tag
          base_version = tuple([int(x) for x in base_version.split(".")])
        File "/private/var/folders/s9/fstqywnd0wj_j0qq9w4b33_c0000gn/T/pip-build-env-2mjl8h74/overlay/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 366, in <listcomp>
          base_version = tuple([int(x) for x in base_version.split(".")])
      ValueError: invalid literal for int() with base 10: ''
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hello-cpp
Failed to build hello-cpp
ERROR: Could not build wheels for hello-cpp, which is required to install pyproject.toml-based projects
```
</details>

**Comment by henryiii** [comment]
Seems okay to me:

<img width="990" alt="Screen Shot 2022-05-19 at 9 34 17 AM" src="https://user-images.githubusercontent.com/4616906/169305998-0c379a46-ca3e-4dc6-9b34-424b26ab0b8a.png">

**Comment by hameer-spire** [comment]
From the log:
> `bdist.macosx--arm64`

It can't calculate the deployment target.

**Comment by henryiii** [comment]
Ugh, Conda's support of building packages with pip is terrible. Generally you should not use conda for development, but only deploy binaries via conda, and that with Conda-build, which sets everything up. You do have `compilers`, which helps.

Wheel should pull the deployment target from the compiled version of Python, which to me sounds like they've messed that up when compiling CPython.

**Comment by henryiii** [comment]
Ping me if I forget about this, my M1 is upgrading to macOS 12.4 at the moment.

**Comment by hameer-spire** [comment]
Hi! I hope I'm not too early, but ping. @henryiii!

I just verified it indeed is macOS or Apple silicon related. It works fine on Linux.

**Comment by kjelljorner** [comment]
I'm relatively sure what causes this. For some reason, `CMAKE_ARGS` includes `-DCMAKE_OSX_DEPLOYMENT_TARGET= ` in an environment with compilers installed. 

```shell
$ echo $CMAKE_ARGS 
-DCMAKE_AR=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_CXX_COMPILER_AR=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_C_COMPILER_AR=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-ar -DCMAKE_RANLIB=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_C_COMPILER_RANLIB=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-ranlib -DCMAKE_LINKER=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-ld -DCMAKE_STRIP=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-strip -DCMAKE_INSTALL_NAME_TOOL=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-install_name_tool -DCMAKE_LIBTOOL=/opt/homebrew/Caskroom/mambaforge/base/envs/dlf/bin/arm64-apple-darwin20.0.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

I got it running with the following command (to build wheels)
```shell
$ CMAKE_ARGS=$(echo $CMAKE_ARGS | sed "s/-DCMAKE_OSX_DEPLOYMENT_TARGET= -/-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -/") python -m build --wheel
```

I think you can safely say that this is an issue on the conda-forge side, but might be good to safeguard for an empty string in scikit-build around here https://github.com/scikit-build/scikit-build/blob/24ad55cc2a67a9f041c1ecde4989cd948c5e627f/skbuild/setuptools_wrap.py#L539

**Comment by kjelljorner** [comment]
Ok, I think the issue is that conda env activation will use `MACOSX_DEPLOYMENT_TARGET` to set `DCMAKE_OSX_DEPLOYMENT_TARGET` in this file https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/main/recipe/activate-clang.sh. I tried `MACOSX_DEPLOYMENT_TARGET=11.0` before activating my conda env and it works.

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
