### ISSUE TITLE
Improve cmaker exception

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#75]
When there is a problem building python module, report "human-friendly" error

**Comment by opadron** [comment]
Could you elaborate?

Are we not handling error cases that we should?
Are we not giving good enough diagnostic messages?

**Comment by jcfr** [comment]
For example, in addition of the following stacktrace:

```
ERROR: tests.test_tower_of_babel.test_tbabel_builds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jcfr/.virtualenvs/scikit-build/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jcfr/Projects/scikit-build/tests/test_tower_of_babel.py", line 32, in test_tbabel_builds
    exec(fp.read())
  File "<string>", line 11, in <module>
  File "/home/jcfr/Projects/scikit-build/skbuild/distutils_wrap.py", line 133, in setup
    cmkr.make(make_args)
  File "/home/jcfr/Projects/scikit-build/skbuild/cmaker.py", line 320, in make
    rtn = subprocess.check_call(cmd, cwd=CMAKE_BUILD_DIR)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release']' returned non-zero exit status 2
```

Displaying the following additional information would be helpfull:
* Command allowing to reproduce the problem ... in a format that could be easily copied
* Value of CMAKE_C_COMPILER, CMAKE_CXX_COMPILER
* Path to CMakeCache.txt
* Working directory
