### ISSUE TITLE
scikit-build wheel is missing resources

### ISSUE THREAD

**Issue by bnavigator** [scikit-build/scikit-build#786]
The published wheel is missing the resources/cmake folder, breaks, e.g., Slycot:

```
[    3s] + /usr/bin/python3.8 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build .
[    3s] Processing /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0
[    3s]   Preparing metadata (pyproject.toml): started
[    3s]   Running command Preparing metadata (pyproject.toml)
[    3s]   running dist_info
[    3s]   creating /tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info
[    3s]   writing /tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info/PKG-INFO
[    3s]   writing dependency_links to /tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info/dependency_links.txt
[    3s]   writing requirements to /tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info/requires.txt
[    3s]   writing top-level names to /tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info/top_level.txt
[    3s]   writing manifest file '/tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info/SOURCES.txt'
[    3s]   reading manifest file '/tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info/SOURCES.txt'
[    3s]   reading manifest template 'MANIFEST.in'
[    3s]   adding license file 'COPYING'
[    3s]   adding license file 'AUTHORS'
[    3s]   writing manifest file '/tmp/pip-modern-metadata-4ikcjvai/slycot.egg-info/SOURCES.txt'
[    3s]   creating '/tmp/pip-modern-metadata-4ikcjvai/slycot-0.5.0.dist-info'
[    3s]   Preparing metadata (pyproject.toml): finished with status 'done'
[    3s] Building wheels for collected packages: slycot
[    3s]   Building wheel for slycot (pyproject.toml): started
[    3s]   Running command Building wheel for slycot (pyproject.toml)
[    4s] 
[    4s] 
[    4s]   --------------------------------------------------------------------------------
[    4s]   -- Trying "Unix Makefiles" generator
[    4s]   --------------------------------
[    4s]   ---------------------------
[    4s]   ----------------------
[    4s]   -----------------
[    4s]   ------------
[    4s]   -------
[    4s]   --
[    4s]   Not searching for unused variables given on the command line.
[    4s]   -- The C compiler identification is GNU 12.2.1
[    4s]   -- Detecting C compiler ABI info
[    4s]   -- Detecting C compiler ABI info - done
[    4s]   -- Check for working C compiler: /usr/bin/cc - skipped
[    4s]   -- Detecting C compile features
[    4s]   -- Detecting C compile features - done
[    4s]   -- The Fortran compiler identification is GNU 12.2.1
[    4s]   -- Detecting Fortran compiler ABI info
[    4s]   -- Detecting Fortran compiler ABI info - done
[    4s]   -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
[    4s]   -- Configuring done
[    4s]   -- Generating done
[    4s]   -- Build files have been written to: /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0/_cmake_test_compile/build
[    4s]   --
[    4s]   -------
[    4s]   ------------
[    4s]   -----------------
[    4s]   ----------------------
[    4s]   ---------------------------
[    4s]   --------------------------------
[    4s]   -- Trying "Unix Makefiles" generator - success
[    4s]   --------------------------------------------------------------------------------
[    4s] 
[    4s]   Configuring Project
[    4s]     Working directory:
[    4s]       /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0/_skbuild/linux-x86_64-3.8/cmake-build
[    4s]     Command:
[    4s]       cmake /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0 -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/home/abuild/rpmbuild/BUILD/slycot-0.5.0.0/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/usr/lib/python3.8/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3.8 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib64/libpython3.8.so -DPython_EXECUTABLE:PATH=/usr/bin/python3.8 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/lib64/python3.8/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3.8 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/lib64/python3.8/site-packages/numpy/core/include -DSLYCOT_VERSION:STRING=0.5.0 -DGIT_REVISION:STRING=e162b5fc3027a9c288a4f820a626f269eb63f9e0 -DISRELEASE:STRING=True -DFULL_VERSION=0.5.0.gite162b5f -DCMAKE_BUILD_TYPE:STRING=Release
[    4s] 
[    4s]   -- The C compiler identification is GNU 12.2.1
[    4s]   -- Detecting C compiler ABI info
[    4s]   -- Detecting C compiler ABI info - done
[    4s]   -- Check for working C compiler: /usr/bin/cc - skipped
[    4s]   -- Detecting C compile features
[    4s]   -- Detecting C compile features - done
[    4s]   -- The Fortran compiler identification is GNU 12.2.1
[    4s]   -- Detecting Fortran compiler ABI info
[    4s]   -- Detecting Fortran compiler ABI info - done
[    4s]   -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
[    4s]   -- Found PythonLibs: /usr/lib64/libpython3.8.so (found version "3.8.15")
[    4s]   CMake Error at CMakeLists.txt:15 (find_package):
[    4s]     By not providing "FindPythonExtensions.cmake" in CMAKE_MODULE_PATH this
[    4s]     project has asked CMake to find a package configuration file provided by
[    4s]     "PythonExtensions", but CMake did not find one.
[    4s] 
[    4s]     Could not find a package configuration file provided by "PythonExtensions"
[    4s]     with any of the following names:
[    4s] 
[    4s]       PythonExtensionsConfig.cmake
[    4s]       pythonextensions-config.cmake
[    4s] 
[    4s]     Add the installation prefix of "PythonExtensions" to CMAKE_PREFIX_PATH or
[    4s]     set "PythonExtensions_DIR" to a directory containing one of the above
[    4s]     files.  If "PythonExtensions" provides a separate development package or
[    4s]     SDK, be sure it has been installed.
[    4s] 
[    4s] 
[    4s]   -- Configuring incomplete, errors occurred!
[    4s]   See also "/home/abuild/rpmbuild/BUILD/slycot-0.5.0.0/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
[    4s]   Traceback (most recent call last):
[    4s]     File "/usr/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 632, in setup
[    4s]       env = cmkr.configure(
[    4s]     File "/usr/lib/python3.8/site-packages/skbuild/cmaker.py", line 333, in configure
[    4s]       raise SKBuildError(
[    4s] 
[    4s]   An error occurred while configuring with CMake.
[    4s]     Command:
[    4s]       cmake /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0 -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/home/abuild/rpmbuild/BUILD/slycot-0.5.0.0/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/usr/lib/python3.8/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3.8 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib64/libpython3.8.so -DPython_EXECUTABLE:PATH=/usr/bin/python3.8 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/lib64/python3.8/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3.8 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/lib64/python3.8/site-packages/numpy/core/include -DSLYCOT_VERSION:STRING=0.5.0 -DGIT_REVISION:STRING=e162b5fc3027a9c288a4f820a626f269eb63f9e0 -DISRELEASE:STRING=True -DFULL_VERSION=0.5.0.gite162b5f -DCMAKE_BUILD_TYPE:STRING=Release
[    4s]     Source directory:
[    4s]       /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0
[    4s]     Working directory:
[    4s]       /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0/_skbuild/linux-x86_64-3.8/cmake-build
[    4s]   Please see CMake's output for more information.
[    4s]   error: subprocess-exited-with-error
[    4s]   
[    4s]   × Building wheel for slycot (pyproject.toml) did not run successfully.
[    4s]   │ exit code: 1
[    4s]   ╰─> See above for output.
[    4s]   
[    4s]   note: This error originates from a subprocess, and is likely not a problem with pip.
[    4s]   full command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmph2m056q9
[    4s]   cwd: /home/abuild/rpmbuild/BUILD/slycot-0.5.0.0
[    4s]   Building wheel for slycot (pyproject.toml): finished with status 'error'
[    4s]   ERROR: Failed building wheel for slycot
[    4s] Failed to build slycot
[    4s] ERROR: Failed to build one or more wheels
```

**Comment by bnavigator** [comment]
Fixed by #790
