### ISSUE TITLE
BUG: Python build fails in skbuild

### ISSUE THREAD

**Issue by tbirdso** [scikit-build/scikit-build#805]
## Summary

Two ITK modules have recently failed to build. The error printout appears to point to `skbuild`, possibly due to some dependency update.

## Error Trace

```
running bdist_wheel
running build
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    setup(
  File "C:\P\IPP\venv-38-x64\lib\site-packages\skbuild\setuptools_wrap.py", line 644, in setup
    return upstream_setup(*args, **kw)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\P\IPP\venv-38-x64\lib\site-packages\skbuild\command\bdist_wheel.py", line 40, in run
    super(bdist_wheel, self).run(*args, **kwargs)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
    self.run_command("build")
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\P\IPP\venv-38-x64\lib\site-packages\skbuild\command\build_py.py", line 41, in run
    with distribution_hide_listing(self.distribution):
  File "C:\Python38-x64\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\P\IPP\venv-38-x64\lib\site-packages\skbuild\utils\__init__.py", line 190, in distribution_hide_listing
    old_threshold = distutils_log._global_log.threshold
AttributeError: 'RootLogger' object has no attribute 'threshold'
running build_py
```

The issue appears to lie in this line:

https://github.com/scikit-build/scikit-build/blob/master/skbuild/utils/__init__.py#L230

## Platform Information

Windows 10
Python 3.7 or 3.8 (others not tested)
CMake 3.25.0
Ninja 1.11.1

Python package install printout:
```
created virtual environment CPython3.7.9.final.0-64 in 3987ms
  creator CPython3Windows(dest=C:\P\IPP\venv-37-x64, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\runneradmin\AppData\Local\pypa\virtualenv)
    added seed packages: attrs==22.1.0, delvewheel==1.1.2, distro==1.8.0, future==0.[18](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3566539639/jobs/5993110065#step:6:19).2, itk==5.3.0, itk_core==5.3.0, itk_filtering==5.3.0, itk_io==5.3.0, itk_numerics==5.3.0, itk_registration==5.3.0, itk_segmentation==5.3.0, machomachomangler==0.0.1, numpy==1.21.6, packaging==21.3, pefile==2022.5.30, pip==22.3.1, pyparsing==3.0.9, scikit_build==0.8.1, setuptools==65.6.3, typing_extensions==4.4.0, wheel==0.38.4
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
```

[ITKSplitComponents failure](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3566539639/jobs/5993110065)

[ITKStrain failure](https://github.com/KitwareMedical/ITKStrain/actions/runs/3565229719/jobs/5990863244)

## Other Notes

ITKStrain previously succeeded six days ago for `skbuild==0.8.1`. No changes have been introduced to ITKStrain since that time. It appears that `setuptools` was updated from 65.5.1 to 65.6.3 during that time.

Last successful ITKStrain run: https://github.com/KitwareMedical/ITKStrain/actions/runs/3524638335/jobs/5911290582

```
created virtual environment CPython3.7.9.final.0-64 in 3627ms
  creator CPython3Windows(dest=C:\P\IPP\venv-37-x64, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\runneradmin\AppData\Local\pypa\virtualenv)
    added seed packages: attrs==22.1.0, delvewheel==1.1.1, distro==1.8.0, future==0.[18](https://github.com/KitwareMedical/ITKStrain/actions/runs/3524638335/jobs/5911290582#step:6:19).2, itk==5.3rc4.post4, itk_core==5.3rc4.post4, itk_filtering==5.3rc4.post4, itk_io==5.3rc4.post4, itk_numerics==5.3rc4.post4, itk_registration==5.3rc4.post4, itk_segmentation==5.3rc4.post4, machomachomangler==0.0.1, numpy==1.21.6, packaging==21.3, pefile==2022.5.30, pip==22.3.1, pyparsing==3.0.9, scikit_build==0.8.1, setuptools==65.5.1, typing_extensions==4.4.0, wheel==0.38.4
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
```

This issue blocks ITK remote module updates for v5.3. Any help or discussion is appreciated.

**Comment by tbirdso** [comment]
cc @jcfr @thewtex

**Comment by henryiii** [comment]
Why is that 0.8.1? Have you tried 0.16? Setuptools updated the internal distutils, which in turn now uses the standard lib logging instead of a custom built-in logger. I _think_ we have supported this the last few releases (though there's one more unreleased logging change in master that might help).

**Comment by tbirdso** [comment]
Hi @henryiii , I will update to 0.16.2 and circle back with the result, thanks 👍

**Comment by tbirdso** [comment]
The issue is not present after uploading to scikit-build 0.16.2 in a test environment. Closing as an issue in the ITK remote build process rather than in scikit-build.

https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3568044358/jobs/5996464060
