### ISSUE TITLE
cmake_minimum_required_version not parsed correctly

### ISSUE THREAD

**Issue by tdegeus** [scikit-build/scikit-build#816]
I have 
```python
from skbuild import setup

setup(
    ...
    cmake_minimum_required_version="3.13...3.21",
)
```
which has always worked, up to now.

Which 0.16.3 I get:
```none
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/tdegeus/data/prog/src/prrng/setup.py", line 11, in <module>
      setup(
    File "/home/tdegeus/miniforge3/envs/code_line_jed/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 615, in setup
      if parse_version(cmkr.cmake_version) < parse_version(cmake_minimum_required_version):
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/tdegeus/miniforge3/envs/code_line_jed/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
      return Version(version)
             ^^^^^^^^^^^^^^^^
    File "/home/tdegeus/miniforge3/envs/code_line_jed/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
      raise InvalidVersion(f"Invalid version: '{version}'")
  packaging.version.InvalidVersion: Invalid version: '3.13...3.21'
````

**Comment by henryiii** [comment]
This is due to Packaing 22.0 dropping LegacyVersion, and this was being parsed as a LegacyVersion since it's not a valid Version. Not actually tied to skbuild version.


```PyCon
>>> packaging.__version__
'20.4'
>>> packaging.version.parse("3.13...3.21")
<LegacyVersion('3.13...3.21')>
```

Is there a reason to put the upper limit in there? I think this parameter is likely on the chopping block, as scikit-build-core's TOML specification allows the build system to dynamically decide if it needs the cmake package - this can't be done inside a setup.py argument. And scikit-build-core explicitly requires a normal version for `tool.scikit-build.cmake.minimum-version`.

**Comment by tdegeus** [comment]
True, I don't know how that ended up in my code. I have removed it. 

That being said, it is legal CMake - https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html  - and should thus be supported in my opinion

**Comment by henryiii** [comment]
scikit-build (classic) after #1185 is now a thin wrapper around scikit-build-core's setuptools plugin. Closing all open issues; if this still applies, please reopen or open an issue on scikit-build-core. Thanks!
