### ISSUE TITLE
CMake generates make when ninja is requested?

### ISSUE THREAD

**Issue by ZJaume** [scikit-build/scikit-build#817]
I'm migrating a [project](https://github.com/bitextor/bicleaner-hardrules/pull/7) that uses scikit-build to pyproject file and now seems that CMake is getting confused about ninja.

My pyproject:
```toml
[build-system]
requires = [
    "setuptools>=45.0,<66",
    "cmake>=3.18",
    "scikit-build==0.16.3",
    "ninja",
]
build-backend = "setuptools.build_meta"
```

The setup.py
```python
#!/usr/bin/env python
from skbuild import setup

setup(
    cmake_source_dir="./kenlm",
    cmake_args=[
        "-DKENLM_MAX_ORDER=7",
        "-DFORCE_STATIC=ON",
        "-DENABLE_INTERPOLATE=OFF",
    ]
)
```

When installing with `pip install .` CMake seems to generate that dectects ninja during generation but then it says wrong generator:
```python
Building wheels for collected packages: bicleaner-hardrules
  Building wheel for bicleaner-hardrules (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for bicleaner-hardrules (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]


      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /home/user/hardrules/bicleaner-hardrules/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /home/user/hardrules/bicleaner-hardrules/_skbuild/linux-x86_64-3.7/cmake-build
        Command:
          cmake /home/user/hardrules/bicleaner-hardrules/kenlm -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/home/user/hardrules/bicleaner-hardrules/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.5 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-_3rvvmzi/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/user/hardrules/venv/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/user/hardrules/venv/bin/python3.7 -DPython_ROOT_DIR:PATH=/home/user/hardrules/venv -DPython_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/home/user/hardrules/venv/bin/python3.7 -DPython3_ROOT_DIR:PATH=/home/user/hardrules/venv -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-_3rvvmzi/overlay/lib/python3.7/site-packages/ninja/data/bin/ninja -DKENLM_MAX_ORDER=7 -DFORCE_STATIC=ON -DENABLE_INTERPOLATE=OFF -DCMAKE_BUILD_TYPE:STRING=Release

      CMake Error: Error: generator : Ninja
      Does not match the generator used previously: Unix Makefiles
      Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-_3rvvmzi/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 637, in setup
          languages=cmake_languages,
        File "/tmp/pip-build-env-_3rvvmzi/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 335, in configure
          "An error occurred while configuring with CMake.\n"

      An error occurred while configuring with CMake.
        Command:
          cmake /home/user/hardrules/bicleaner-hardrules/kenlm -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/home/user/hardrules/bicleaner-hardrules/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.5 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-_3rvvmzi/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/user/hardrules/venv/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/user/hardrules/venv/bin/python3.7 -DPython_ROOT_DIR:PATH=/home/user/hardrules/venv -DPython_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/home/user/hardrules/venv/bin/python3.7 -DPython3_ROOT_DIR:PATH=/home/user/hardrules/venv -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-_3rvvmzi/overlay/lib/python3.7/site-packages/ninja/data/bin/ninja -DKENLM_MAX_ORDER=7 -DFORCE_STATIC=ON -DENABLE_INTERPOLATE=OFF -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /home/user/hardrules/bicleaner-hardrules/kenlm
        Working directory:
          /home/user/hardrules/bicleaner-hardrules/_skbuild/linux-x86_64-3.7/cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bicleaner-hardrules
Failed to build bicleaner-hardrules
ERROR: Could not build wheels for bicleaner-hardrules, which is required to install pyproject.toml-based projects
```

When using the old full `setup.py`  configuration it was working. I also tried to compile the submodule `kenlm` manually with ninja and works:
```
cd kenlm
cmake .. -G Ninja -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/home/user/hardrules/venv -DFORCE_STATIC=ON -DENABLE_INTERPOLATE=OFF
ninja
```

I know that pyproject is not fully supported and usning `make` as generator seems to work, so there's no major issue for me. But I thought it could be a bug.

Thank you for this wonderful project!

**Comment by ZJaume** [comment]
Sorry, I forgot to delete `_skbuild` directory that contained old runs.
