### ISSUE TITLE
0.16.5 regression: `AttributeError: module 'cmake' has no attribute 'CMAKE_BIN_DIR'`

### ISSUE THREAD

**Issue by robertmaynard** [scikit-build/scikit-build#849]
Updating to 0.16.5 introduces a regression where scikit-build can no longer find cmake:

```
Traceback (most recent call last):
  File "/home/user/cudf/python/cudf/setup.py", line 7, in <module>
    from skbuild import setup
  File "/home/user/envs/cudfdev/lib/python3.10/site-packages/skbuild/__init__.py", line 10, in <module>
    from .setuptools_wrap import setup
  File "/home/user/envs/cudfdev/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 39, in <module>
    from . import cmaker
  File "/home/user/envs/cudfdev/lib/python3.10/site-packages/skbuild/cmaker.py", line 25, in <module>
    from .constants import (
  File "/home/user/envs/cudfdev/lib/python3.10/site-packages/skbuild/constants.py", line 33, in <module>
    CMAKE_DEFAULT_EXECUTABLE = _get_cmake_executable()
  File "/home/user/envs/cudfdev/lib/python3.10/site-packages/skbuild/constants.py", line 19, in _get_cmake_executable
    path = f"{cmake.CMAKE_BIN_DIR}/cmake"
AttributeError: module 'cmake' has no attribute 'CMAKE_BIN_DIR'
```

**Comment by robertmaynard** [comment]
This is inside a conda env.

**Comment by henryiii** [comment]
Dupe of #845, fixed in #848. Do you have a cmake folder or cmake.py locally?

**Comment by robertmaynard** [comment]
The project has a `cmake` sub-folder

**Comment by henryiii** [comment]
Yep, that'll break it. I've yanked 0.16.5, a patched 0.16.6 will be out soon. Ironically was a little slow because I was in the Scikit-build Community Meeting. :)

**Comment by robertmaynard** [comment]
Should we expect a scikit-build-feedstock rebuild + patch for 0.16.5 or should we expect a 0.16.6 release?

**Comment by henryiii** [comment]
Ahh, in conda. I'll push a release pretty quickly, and that's likely the best way to get it into conda. Otherwise I have to add a patch and then remove a patch, or get it marked broken.

**Comment by robertmaynard** [comment]
Closing so we can keep all discussions in #845 845
