### ISSUE TITLE
Missing macos version on OSX

### ISSUE THREAD

**Issue by bryevdv** [scikit-build/scikit-build#911]
Seeing directories computed like
```
_skbuild/macosx--x86_64-3.9/cmake-install/include/rapids/cub/block/specializations/block_reduce_raking_commutative_only.cuh -> _skbuild/macosx--x86_64-3.9/setuptools/bdist.macosx--x86_64/wheel/
```
i.e. with no proper OSX version: `macosx--x86_64-3.9`

This subsequently causes the final install step to fail:
```
    File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 281, in get_tag
      plat_name = get_platform(self.bdist_dir)
    File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 52, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 399, in calculate_macosx_platform_tag
      base_version = tuple(int(x) for x in base_version.split("."))
    File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 399, in <genexpr>
      base_version = tuple(int(x) for x in base_version.split("."))
  ValueError: invalid literal for int() with base 10: ''
```

I am not 100% sure this problem lies in scikit-build specifically. There are so many places that implement or vendor something like `get_platform`. But the first concrete thread I can find to pull on is the skbuild directory paths with the incomplete version, so this seems like the best place to start. 

I have tried using earlier versions of setuptools as well as downgrading skbuild to 0.15 and 0.14. This build used to function on OSX so it's not clear what might have changed where. Please let me know what additional information I can try to collect.

**Comment by henryiii** [comment]
Could it be that you've set `MACOSX_DEPLOYMENT_TARGET` to an empty string?

**Comment by bryevdv** [comment]
Hi @henryiii no I've never heard of that env var and just confirmed it is not set to anything at all.

**Comment by henryiii** [comment]
What is the output of these two commands for you?

```console
$ python3 -c "import platform; print(platform.mac_ver())"
('13.2.1', ('', '', ''), 'x86_64')
$ python -c 'import skbuild.constants; print(skbuild.constants.skbuild_plat_name())'
macosx-13.0-x86_64
```

**Comment by henryiii** [comment]
That looks fine. I can't see any setting of `CMAKE_OSX_DEPLOYMENT_TARGET` (in CMAKE_ARGS or similar). I added a quick check to verify version is not empty, maybe that will trigger (which would indicate that `CMAKE_OSX_DEPLOYMENT_TARGET` is being passed somewhere).

**Comment by bryevdv** [comment]
🙏 thanks @henryiii I will test things out again when that change makes it into the next skbuild release

**Comment by bryevdv** [comment]
@henryiii well, I tried adding that assertion to my installed `skbuild` (0.16.7) manually. I assume if it was hit it would trigger before this?
```
  -- Build files have been written to: /Users/bryan/work/legate.core/_skbuild/macosx--x86_64-3.9/cmake-build
  [1/191] cd /Users/bryan/work/legate.core/_skbuild/macosx--x86_64-3.9/cmake-build && /private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-24vpo_be/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake -DLegion_NETWORKS="" -DGASNet_CONDUIT="" -DLegion_USE_CUDA="OFF" -DLegion_USE_OpenMP="OFF" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_C_COMPILER=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-clang -P /Users/bryan/work/legate.core/cmake/generate_install_info_py.cmake
```

**Comment by henryiii** [comment]
As long as you’re not doing an isolated build, yes.

**Comment by henryiii** [comment]
You could also add a print statement there if you’re doing it manually

**Comment by bryevdv** [comment]
ah, right, it is doing an isolated build.

**Comment by bryevdv** [comment]
@henryiii the build starts working with `scikit-build<0.14`
```diff
diff --git a/pyproject.toml b/pyproject.toml
index c186fc7..e1aaa0b 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -17,7 +17,7 @@ requires = [
     "wheel",
     "ninja",
     "setuptools",
-    "scikit-build>=0.13.1",
+    "scikit-build<0.14",
     "cmake>=3.22.1,!=3.23.0,!=3.25.0",
 ]
```
yields correct location:
```
  -- Build files have been written to: /Users/bryan/work/legate.core/_skbuild/macosx-13.0-x86_64-3.9/cmake-build
  [1/191] cd /Users/bryan/work/legate.core/_skbuild/macosx-13.0-x86_64-3.9/cmake-build && /private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-4awqr3q0/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake -DLegion_NETWORKS="OFF" -DGASNet_CONDUIT="" -DLegion_USE_CUDA="" -DLegion_USE_OpenMP="" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_C_COMPILER=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-clang -P /Users/bryan/work/legate.core/cmake/generate_install_info_py.cmake
```
It does *not* work if I raise to `"scikit-build<0.15"` (full build still fails, but at least not for this reason)

**Comment by henryiii** [comment]
Could you check 0.17, just released?

**Comment by henryiii** [comment]
Hmm, 0.14.1 fixed an issue with `SKBUILD_CONFIGURE_OPTIONS` not being read. I wonder if you have a `SKBUILD_CONFIGURE_OPTIONS`, maybe with `CMAKE_OSX_DEPLOYMENT_TARGET` in it?

**Comment by bryevdv** [comment]
@henryiii yes the assertion is hit after an update to 0.17
```
Building wheels for collected packages: legate.core
  Created temporary directory: /private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-wheel-d25cm0bp
  Destination directory: /private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-wheel-d25cm0bp
  Running command Building wheel for legate.core (pyproject.toml)
  /private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-sxw1krg7/overlay/lib/python3.9/site-packages/setuptools/dist.py:547: UserWarning: Normalizing '23.03.00.dev+87.g11ff2f3.dirty' to '23.3.0.dev0+87.g11ff2f3.dirty'
    warnings.warn(tmpl.format(**locals()))
  Traceback (most recent call last):
    File "/Users/bryan/anaconda/envs/py39/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/bryan/anaconda/envs/py39/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/bryan/anaconda/envs/py39/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-sxw1krg7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 413, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-sxw1krg7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-sxw1krg7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-sxw1krg7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 23, in <module>
    File "/private/var/folders/g5/0qds8m2n00qcfqkfxggy2jf40000gn/T/pip-build-env-sxw1krg7/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 571, in setup
      assert version, "CMAKE_OSX_DEPLOYMENT_TARGET must not be empty if specified"
  AssertionError: CMAKE_OSX_DEPLOYMENT_TARGET must not be empty if specified
  error: subprocess-exited-with-error
```

**Comment by bryevdv** [comment]
> Does 0.14.0 exactly work?

No 0.14 also fails exhibiting the same malformed directory locations

I did a `grep -r` for `SKBUILD_CONFIGURE_OPTIONS` I can't find it used or set anywhere, and its not set in my local env either.

**Comment by henryiii** [comment]
Any sign of CMAKE_OSX_DEPLOYMENT_TARGET anywhere, maybe `env | grep` for it?

**Comment by bryevdv** [comment]
Uh, OK I guess we found the culprit: 
```
py39 ❯ envg CMAKE_OSX_DEPLOYMENT_TARGET
CMAKE_ARGS=-DCMAKE_AR=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_CXX_COMPILER_AR=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_C_COMPILER_AR=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_RANLIB=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_C_COMPILER_RANLIB=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_LINKER=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-ld -DCMAKE_STRIP=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-strip -DCMAKE_INSTALL_NAME_TOOL=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-install_name_tool -DCMAKE_LIBTOOL=/Users/bryan/anaconda/envs/py39/bin/x86_64-apple-darwin13.4.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```
And if I delete that env var then the build seems to work. 

I never set this tho, it seems to be an artifact of activating the conda env.

**Comment by henryiii** [comment]
Conda's environments are not designed for building code - I'd generally avoid building using them. Only pre-build packages via conda-build should be used inside conda recipes, ideally.

Anyway, could you dump your conda environment? Specifically wanting to know what is installed related to compilers (`compilers`, `toolchain*`, `clang*`, that sort of thing). This is a clearly broken environment, though if CMake ignores an empty value here, we could too. I'm not sure if it does.

**Comment by bryevdv** [comment]
> Conda's environments are not designed for building code - I'd generally avoid building using them

I'm not sure I agree with this sentiment, though it's certain that there are issues with conda compilers under certain situations. 

Anyway here is the current conda env:

<details>

```
py39 ❯ conda list
# packages in environment at /Users/bryan/anaconda/envs/py39:
#
# Name                    Version                   Build  Channel
accessible-pygments       0.0.4                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
appnope                   0.1.3                    pypi_0    pypi
arrow-cpp                 11.0.0          h694c41f_13_cpu    conda-forge
asttokens                 2.2.1                    pypi_0    pypi
attrs                     22.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.6.26               hcaaecf5_1    conda-forge
aws-c-cal                 0.5.21               hf54dd2f_2    conda-forge
aws-c-common              0.8.14               hb7f2c08_0    conda-forge
aws-c-compression         0.2.16               h99c63db_5    conda-forge
aws-c-event-stream        0.2.20               h0ae4c0f_4    conda-forge
aws-c-http                0.7.6                hcdd7835_0    conda-forge
aws-c-io                  0.13.19              had634fe_3    conda-forge
aws-c-mqtt                0.8.6               ha4e05e3_12    conda-forge
aws-c-s3                  0.2.7                hba8c00c_1    conda-forge
aws-c-sdkutils            0.1.8                h99c63db_0    conda-forge
aws-checksums             0.1.14               h99c63db_5    conda-forge
aws-crt-cpp               0.19.8              h8b21dc2_12    conda-forge
aws-sdk-cpp               1.10.57              h0d082ec_8    conda-forge
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.0                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
brotlipy                  0.7.0           py39ha30fb19_1005    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
c-compiler                1.5.2                hbf74d83_0    conda-forge
ca-certificates           2023.01.10           hecd8cb5_0
cctools                   973.0.1             h76f1dac_13    conda-forge
cctools_osx-64            973.0.1             hcc6d90d_13    conda-forge
certifi                   2022.12.7        py39hecd8cb5_0
cffi                      1.15.1           py39h131948b_3    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
clang                     14.0.6               h694c41f_0    conda-forge
clang-14                  14.0.6          default_h55ffa42_0    conda-forge
clang-format              14.0.6          default_h55ffa42_0    conda-forge
clang-format-14           14.0.6          default_h55ffa42_0    conda-forge
clang-tools               14.0.6          default_h55ffa42_0    conda-forge
clang_osx-64              14.0.6               h3113cd8_6    conda-forge
clangxx                   14.0.6          default_h55ffa42_0    conda-forge
clangxx_osx-64            14.0.6               h6f97653_6    conda-forge
cmake                     3.26.2               h4032537_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
compiler-rt               14.0.6               h613da45_0    conda-forge
compiler-rt_osx-64        14.0.6               hab78ec2_0    conda-forge
coverage                  7.2.2            py39ha30fb19_0    conda-forge
cryptography              40.0.1           py39hbeae22c_0    conda-forge
curl                      7.88.1               h6df9250_1    conda-forge
cxx-compiler              1.5.2                hb8565cd_0    conda-forge
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
distlib                   0.3.6              pyhd8ed1ab_0    conda-forge
distro                    1.8.0              pyhd8ed1ab_0    conda-forge
docutils                  0.19                     pypi_0    pypi
doxygen                   1.9.6                h8a4c099_0    conda-forge
exceptiongroup            1.1.1              pyhd8ed1ab_0    conda-forge
executing                 1.2.0                    pypi_0    pypi
expat                     2.5.0                hf0c8a7f_1    conda-forge
fastjsonschema            2.16.3                   pypi_0    pypi
filelock                  3.10.7             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
git                       2.40.0          pl5321h33fe9b8_1    conda-forge
glog                      0.6.0                h8ac2a54_0    conda-forge
identify                  2.5.22             pyhd8ed1ab_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.1.0              pyha770c72_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipython                   8.12.0                   pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            8.1.0                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
krb5                      1.20.1               h049b76e_0    conda-forge
ld64                      609                 hc6ad406_13    conda-forge
ld64_osx-64               609                 hfd63004_13    conda-forge
legate-core               23.3.0.dev0+87.g11ff2f3.dirty          pypi_0    pypi
legion                    0.1                      pypi_0    pypi
legion-jupyter            0.1                      pypi_0    pypi
libabseil                 20230125.0      cxx17_hf0c8a7f_1    conda-forge
libarrow                  11.0.0          h547aefa_13_cpu    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                hb7f2c08_8    conda-forge
libbrotlidec              1.0.9                hb7f2c08_8    conda-forge
libbrotlienc              1.0.9                hb7f2c08_8    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libclang                  14.0.6          default_h55ffa42_0    conda-forge
libclang-cpp14            14.0.6          default_h55ffa42_0    conda-forge
libclang13                14.0.6          default_hb5731bd_0    conda-forge
libcrc32c                 1.1.2                he49afe7_0    conda-forge
libcurl                   7.88.1               h6df9250_1    conda-forge
libcxx                    16.0.0               h71dddab_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               h7d65743_4    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           11_3_0_h97931a8_31    conda-forge
libgfortran5              12.2.0              he409387_31    conda-forge
libgoogle-cloud           2.8.0                h176059f_1    conda-forge
libgrpc                   1.52.1               h5bc3d57_1    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libllvm11                 11.1.0               h8fb7429_5    conda-forge
libllvm14                 14.0.6               h5b596cc_1    conda-forge
libnghttp2                1.52.0               he2ab024_0    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libprotobuf               3.21.12              hbc0c0cd_0    conda-forge
libsqlite                 3.40.0               ha978bb4_0    conda-forge
libssh2                   1.10.0               h47af595_3    conda-forge
libthrift                 0.18.1               h16802d8_0    conda-forge
libutf8proc               2.8.0                hb7f2c08_0    conda-forge
libuv                     1.44.2               hac89ed1_0    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               16.0.0               h61d9ccf_0    conda-forge
llvm-tools                14.0.6               h5b596cc_1    conda-forge
llvmlite                  0.39.1           py39had167e2_1    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
make                      4.3                  h22f3db7_1    conda-forge
markdown                  3.3.7                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdit-py-plugins           0.3.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
mock                      5.0.1              pyhd8ed1ab_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
mypy                      1.1.1            py39ha30fb19_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
myst-parser               1.0.0                    pypi_0    pypi
nbclient                  0.7.3                    pypi_0    pypi
nbconvert                 7.3.0                    pypi_0    pypi
nbformat                  5.8.0                    pypi_0    pypi
nbsphinx                  0.9.1                    pypi_0    pypi
ncurses                   6.3                  h96cf925_1    conda-forge
ninja                     1.11.1               hb8565cd_0    conda-forge
nodeenv                   1.7.0              pyhd8ed1ab_0    conda-forge
numba                     0.56.4           py39hf6b9d82_0    conda-forge
numpy                     1.23.5           py39hdfa1d0c_0    conda-forge
openblas                  0.3.21          openmp_hbefa662_3    conda-forge
openmpi                   4.1.5              h4fe9131_101    conda-forge
openssl                   3.1.0                hfd90126_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
orc                       1.8.3                ha9d861c_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandoc                    3.1.1                h9d075a6_0    conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3                    pypi_0    pypi
pcre2                     10.40                h1c4e4bc_0    conda-forge
perl                      5.32.1          2_h0d85af4_perl5    conda-forge
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
pre-commit                3.2.1              pyha770c72_0    conda-forge
prompt-toolkit            3.0.38                   pypi_0    pypi
psutil                    5.9.4            py39ha30fb19_0    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyarrow                   11.0.0          py39h56e7202_13_cpu    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydata-sphinx-theme       0.13.3                   pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.2              pyhd8ed1ab_0    conda-forge
pytest-cov                4.0.0              pyhd8ed1ab_0    conda-forge
pytest-lazy-fixture       0.6.3                      py_0    conda-forge
pytest-mock               3.10.0             pyhd8ed1ab_0    conda-forge
python                    3.9.16          h709bd14_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      3_cp39    conda-forge
pyyaml                    6.0              py39ha30fb19_5    conda-forge
pyzmq                     25.0.2                   pypi_0    pypi
re2                       2023.02.02           hf0c8a7f_0    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
rhash                     1.4.3                hac89ed1_0    conda-forge
rust                      1.67.1               h7e1429e_1    conda-forge
rust-std-x86_64-apple-darwin 1.67.1               h059895a_1    conda-forge
scikit-build              0.16.7                   pypi_0    pypi
scipy                     1.10.1           py39h8a15683_0    conda-forge
setuptools                61.0.0                   pypi_0    pypi
sigtool                   0.1.3                h88f4db0_0    conda-forge
six                       1.16.0                   pypi_0    pypi
snappy                    1.1.10               h225ccf5_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.4                      pypi_0    pypi
sphinx                    6.1.3                    pypi_0    pypi
sphinx-copybutton         0.5.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
stack-data                0.6.2                    pypi_0    pypi
tapi                      1100.0.11            h9ce4665_0    conda-forge
tifffile                  2023.3.21                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.2                      pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
types-docutils            0.19.1.7           pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ukkonen                   1.0.1            py39h92daf61_3    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
virtualenv                20.21.0            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hfd90126_4    conda-forge
zstd                      1.5.2                hbc0c0cd_6    conda-forge
```

</details>

**Comment by henryiii** [comment]
Yikes, that's a giant environment with a mix of sources. I've recommend keeping your environments small and focused, with environment.yml's for each one, and never touch the default environment. I guess the place to start is with the formula that have "clang" in them. Someone is setting `-DCMAKE_OSX_DEPLOYMENT_TARGET=$VARIABLE_DOESNT_EXIST` somewhere in its `activate.sh`. If you look in `<conda_folder>/base/envs/<env_name>/etc/conda/activate.d/`, you can actually see all the installed activation scripts. One of those is broken.

What I meant was, conda environments are not designed to allow users _who are not writing recipes_ to build software via pip. It's a binary distribution format with no "user compile" option. Conda ships it's own compiler stack (which until we added a "compilers" package a year to two ago, there wan't really a user-focused way to activate them for general use). A huge portion of bugs related to compiling in pybind11 come from people trying to mix system compilers with conda environments. CMAKE_GENERATOR is set incorrectly. MSVC is incorrectly activated. Etc. As long as you don't build code, or make recipes, it works fine, but it takes care to build inside.

**Comment by bryevdv** [comment]
> never touch the default environment. 

This isn't a default environment

> small and focused

This is a development environment, for developers of this large library. It needs everything requried to build the C++, CUDA, Cython, and Python components, as well as run the tests, and build both the C++ and Python documentation. 

As for splitting up environments, we do. Between all the combinatons of: platform, conda compilers (or not), cuda version, OpenMPI (or not), UCX (or not), etc. we generate 276 distinct env file variations. We use conda because we need to manage that complexity for developers. But it's not really practical to subdivide that even further. 

 > What I meant was, conda environments are not designed to allow users who are not writing recipes to build software via pip.

I guess? I am the original author of conda. While I haven't worked on conda in over ten years, I've been pip installing into conda envs sine 2012. I've been using conda envs to support *developer* workflows for large cross-runtime libraries since 2013. I'm aware of other projects that successfully use conda envs as the basis of developer workflows. I think you are overstating things here, but we can agree to disagree. 

> One of those is broken.

It's clang:

```
base ❯ rg CMAKE_OSX_DEPLOYMENT_TARGET
activate_clang_osx-64.sh
136:_CMAKE_ARGS="${_CMAKE_ARGS} -DCMAKE_OSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET}"
```

**Comment by henryiii** [comment]
Apologies, I didn't see a clear environment name and there were a lot of things like Jupyter, pandoc, and mypy that didn't look very focused toward one project. I didn't mean to say you can't compile for conda, I just said it "takes care". I've also shipped development environments with conda that people could use to build in; but it does require some setup (like installing the compilers package, making sure it's properly activated, and such). And shipping scikit-build, scikit-build-core, and pybind11 has exposed me to a lot of users who aren't very sure of what they are doing and just take default anaconda and try to build with it. And I've also seen quite a few bugs especially in the CMake integration (like `CMAKE_GENERATOR` being set to "make" by conda-build regardless of whether make is installed) which have made supporting them a challenge at times. I do maintain a dozen or more conda-forge recipes, and nearly always use it when teaching.

If it can be fixed in https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/102, then I think this will just resolve itself. We can also check to see if CMake does ignore an empty value (which I rather expect since other things aren't broken, though it's not mentioned in the docs), and mimic that behavior in scikit-build.
